import { SeedArticle } from '../types';

// Added out-of-band from the regular a-f / g-m / n-s / t-z shards: the
// environment that produced this commit had its local disk full (Bash and
// local file writes both failed with ENOSPC), so the large existing shard
// files could not be safely rewritten in full. Functionally identical to
// a shard file - spread into GUIDE_ARTICLES the same way in index.ts. A
// maintainer can fold these into a-f.ts (Eastlink) and g-m.ts (Iberia)
// whenever convenient; there is no functional need to.
export const GuidesRecent: SeedArticle[] = [
  {
    title: "The Eastlink Data Breach: What Nearly 75,000 Cable, Internet, and Phone Customers Should Know",
    slug: "eastlink-2026-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "eastlink-2026-data-breach"],
    body: `Eastlink, the trade name of Bragg Communications Inc. and one of Canada's largest privately held telecom providers, told customers in late August 2026 that it had suffered a data breach affecting roughly 75,000 accounts. The company says suspicious activity was detected overnight between August 26 and 27, and it began emailing affected customers on the evening of Friday, August 28 — with letters and additional outreach following in the days after for customers it hadn't been able to reach by email, including people with older, historical accounts that are no longer active.

According to Eastlink, the exposed information spans internet, television, and home-phone accounts and includes customer names, contact details such as addresses, phone numbers, and email addresses, account numbers, and account PINs. The company says it does not believe full credit card numbers or online banking information were accessed. As a precaution, Eastlink temporarily shut down some customer-facing platforms on its website and mobile app while it investigated, and it has said it is continuing to work through notifying every affected customer.

It's worth understanding why a breach like this matters even without a stolen credit card number in the mix. A name, account number, and PIN are exactly the pieces of information a legitimate call center normally uses to verify that the person calling is really the account holder — which means a scammer who has all three can potentially talk their way past a telecom company's own customer-service verification, impersonating a customer to redirect service, request a SIM or equipment change, or extract even more account detail. That same combination of real name, real account number, and real contact information also makes a convincing prop for a follow-up phishing call, text, or email that references an actual Eastlink account to sound legitimate — a well-documented pattern that shows up after nearly every large telecom breach.

If you're an Eastlink customer, current or former, a few concrete steps are worth taking regardless of whether you've already received a notice. Change your Eastlink account PIN and online password, doing so by logging in directly through eastlink.ca or the official app rather than clicking any link in an email, even one that looks like it came from Eastlink. Treat any unsolicited call, text, or email that references your Eastlink account, address, or a recent bill and then asks you to "verify" your PIN, password, or a one-time passcode as a probable scam — a company that already has your account information does not need you to read sensitive details back to it. Keep an eye on your bank and card statements for small, unfamiliar charges in the weeks ahead, since exposed contact and account details are often combined with information from other sources to attempt fraud elsewhere, even when the original breach didn't include financial data directly. And be skeptical of any message offering to "help you claim compensation" or "check if you were affected" that isn't from Eastlink's own verified channels — breach news reliably draws a second wave of scammers impersonating the breached company itself.

If you want to confirm whether your account was affected or ask about the investigation, contact Eastlink directly through the customer service number printed on a past bill or through eastlink.ca, not a number found through an online search or a link in a text message. Canadian residents who spot a suspicious call, text, or email referencing this breach can report it to the Canadian Anti-Fraud Centre at 1-888-495-8501 or antifraudcentre-centreantifraude.ca; U.S. residents can report phishing and identity theft attempts to the FTC at ReportFraud.ftc.gov.`,
    sourceUrl: "https://www.cbc.ca/news/canada/nova-scotia/eastlink-data-breach-august-2026-9.7325413",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Cable_Modem.JPG?width=1200",
    coverImageCredit: "Photo: Sensibilitat Sensibilite, CC BY 3.0, via Wikimedia Commons",
    coverImagePosition: 50,
    // representative photo — generic cable modem/router, not Eastlink's own equipment; replace with an exact match if found
  },
  {
    title: "The Iberia Airlines Data Breach: How a Hacked Supplier Exposed Frequent-Flyer Customer Data",
    slug: "iberia-airlines-2025-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "iberia-airlines-2025-data-breach"],
    body: `Iberia, Spain's flag carrier and part of the International Airlines Group, notified customers in late November 2025 of a data security incident — but the airline's own network wasn't the point of entry. Iberia said the exposure traced back to unauthorized access at one of its suppliers, a third-party vendor whose systems held certain Iberia customer data. Days before the airline's own notice went out, someone had already posted on a hacking forum claiming to be selling roughly 77 gigabytes of data allegedly taken from Iberia, which is what first drew public attention to the incident.

According to Iberia, the exposed information includes customer names, email addresses, and Iberia Club (the airline's frequent-flyer loyalty program) membership numbers, with phone numbers exposed for some customers as well. Iberia says account passwords and financial or payment card information were not compromised in the incident.

The breach is a useful reminder that a company doesn't have to be hacked directly for its customers' data to end up exposed — a business can have solid security of its own and still be exposed through a supplier or partner it shares customer data with for billing, marketing, or loyalty-program administration. It's also a reminder that loyalty-program data isn't "harmless" just because it isn't a Social Security number or a credit card: a real name paired with a real frequent-flyer number is enough for a scammer to call or email pretending to be Iberia customer service and ask a customer to "verify" their account, and hijacked airline mileage accounts are a well-established fraud target in their own right, since a stranger who takes one over can redeem the miles for flights or merchandise before the real member ever notices.

Iberia has said it responded by requiring a verification code before any change to the email address tied to an account. Customers can add their own layer of protection: log into your Iberia Club or Iberia.com account directly (never through a link in an email) and change your password even though it wasn't reported as stolen, since a password reused on another site could still put the account at risk; check your Iberia Club mileage balance and recent activity for any redemption you didn't make; and turn on any additional login verification the airline offers. Treat any call, text, or email that cites your Iberia Club number or a recent booking and then asks you to "confirm" a password, one-time code, or full card number as a probable scam — a company that already has that information has no legitimate reason to ask a customer to read it back.

U.S.-based travelers who receive a suspicious message referencing Iberia or this breach can report it to the FTC at ReportFraud.ftc.gov. Customers in Spain or elsewhere in the European Union can also raise concerns with their national data protection authority — in Spain, the Agencia Espanola de Proteccion de Datos.`,
    sourceUrl: "https://www.bleepingcomputer.com/news/security/iberia-discloses-customer-data-leak-after-vendor-security-breach/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/EC-NAZ_IBERIA_Airlines_at_London_Heathrow_Airport_2026-04-04.jpg?width=1200",
    coverImageCredit: "Photo: Robert Cutter, CC BY-SA 4.0, via Wikimedia Commons — an Iberia Airbus at London Heathrow Airport",
    coverImagePosition: 50,
  },
  {
    title: "The Bouygues Telecom Data Breach: What 6.4 Million French Customers Should Know About Exposed IBANs",
    slug: "bouygues-telecom-2025-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "bouygues-telecom-2025-data-breach"],
    body: `Bouygues Telecom, one of France's four major telecom carriers, disclosed in August 2025 that it had detected unauthorized access to its information systems on August 4. What it found was one of the largest telecom breaches France has seen in a decade: personal and account data belonging to roughly 6.4 million customers, including around 5.7 million unique email addresses, had been accessed and stolen.

According to the company and outside researchers who reviewed samples of the stolen data, the exposed information included customer names, home addresses, phone numbers, dates of birth, and — for a significant portion of those affected — IBANs, the international bank account numbers used across Europe to process direct debits and transfers. Bouygues Telecom said credit card numbers and the passwords used to log into customer accounts were not part of what was taken. The company notified affected customers directly and said it had blocked the unauthorized access and increased monitoring of its systems.

An IBAN is a different kind of exposure than a stolen password. In the SEPA direct-debit system used across the euro area, a bank account number combined with a customer's name and address is close to what's needed to set up a recurring direct debit against that account — which is why European regulators and consumer groups treat a leaked IBAN as a real fraud risk, not just a privacy inconvenience. Bouygues Telecom itself warned customers to watch for follow-up scams: fraudulent emails, texts, and phone calls impersonating Bouygues or another trusted company, designed to use the stolen personal details as a prop to extract still more information, like a credit card number or a one-time login code. Bouygues was not alone — Free, another major French carrier, disclosed a comparable breach around the same period, and regulators later fined it tens of millions of euros over the security gaps involved, underscoring that 2025 was a rough year for customer data at France's telecom operators specifically.

If you're a Bouygues Telecom customer, a few steps are worth taking regardless of whether you've received a direct notice. Log into your online banking and watch for any direct debit (prélèvement) you don't recognize — under SEPA rules, you generally have the right to request a no-questions-asked refund of an unauthorized direct debit within eight weeks, and up to thirteen months for one that was outright fraudulent, so don't hesitate to dispute anything unfamiliar with your bank. Consider asking your bank about placing extra verification or a watch on new direct-debit mandates tied to your account. Treat any call, text, or email that references your Bouygues account, a recent bill, or your personal details and then asks you to "confirm" a password, card number, or verification code as a probable scam — a company that already has your information has no legitimate reason to ask you to read it back. And change your Bouygues Telecom account password directly through the official app or bouyguestelecom.fr, not through a link in an email or text.

Customers in France who spot a suspicious message referencing this breach can report it to the national phishing-reporting platform at signal-spam.fr or via the government's Cybermalveillance.gouv.fr service, and can raise data-protection concerns with the CNIL, France's privacy regulator, at cnil.fr. Anyone outside France targeted by a follow-up scam citing this breach can report it to the FTC at ReportFraud.ftc.gov.`,
    sourceUrl: "https://techcrunch.com/2025/08/07/data-breach-at-french-telecom-giant-bouygues-affects-millions-of-customers/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Bouygues_Telecom_Boulogne.JPG?width=1200",
    coverImageCredit: "Photo: Bledard92, CC BY-SA 2.5, via Wikimedia Commons",
    coverImagePosition: 50,
    // representative photo — a Bouygues Telecom storefront, not the company's HQ or breached systems
  },
  {
    title: "The Miljödata Breach: How a Ransomware Attack on One HR Vendor Exposed 1.5 Million Swedish Residents' Data",
    slug: "miljodata-2025-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "miljodata-2025-data-breach"],
    body: `Over the weekend of August 23-24, 2025, a ransomware gang tracked as Datacarry broke into the systems of Miljödata, a Swedish software company whose HR and case-management platform, Adato, is used by roughly 80 percent of Sweden's municipalities and regions to manage employee records, sick leave, and workplace-rehabilitation cases. Miljödata disclosed the intrusion on August 25 and said the attackers had stolen data and were demanding a ransom of about 1.5 bitcoin to keep it from being published. Miljödata did not pay, and on September 13 the stolen files showed up on the group's dark-web leak site — turning what started as a single vendor breach into one of the largest data exposures in Swedish history.

Because Adato is embedded in municipal HR systems rather than customer-facing ones, the people affected weren't Miljödata's own customers — they were roughly 1.5 million public-sector employees and residents whose data those municipalities and regions had entered into the platform on their behalf. Around 200 municipalities and regions were affected, including Stockholm, Gothenburg, Gotland, Halland, Kalmar, Karlstad, Umeå, Luleå, and Skellefteå. The stolen data included full names, phone numbers, home addresses, dates of birth, and personnummer — the Swedish personal identity number used to authenticate almost everything in daily Swedish life, from banking and healthcare to tax filings and BankID logins. For some individuals, the leak went further, exposing sensitive details from workplace sick-leave and rehabilitation cases, including medical certificates and descriptions of occupational injuries.

A personnummer is a far more powerful piece of data than it might sound. Unlike a U.S. Social Security number, which is meant to stay behind the scenes, Sweden's personnummer is used openly and constantly as an identifier — which is exactly why a leaked one, combined with a real name, address, and phone number, is valuable to a scammer. The most direct risk is vishing: someone calling and claiming to be from a bank, government agency, or employer, citing real personal details stolen in the breach to sound credible, and then pressuring the target to approve a BankID authentication request or read back a one-time code — at which point the scammer can drain a bank account or take out a loan in the victim's name. Sweden's privacy regulator, the Authority for Privacy Protection (IMY), announced on November 3, 2025 that it had opened formal GDPR investigations into Miljödata and three of the public bodies that used its platform — the City of Gothenburg, the Municipality of Älmhult, and the Region of Västmanland — over how the data was handled.

If your municipality or employer has confirmed you were affected, or if you work for a Swedish public-sector employer that used Miljödata's Adato system, a few concrete precautions matter most. Never approve a BankID request or read out a verification code because someone who called or texted you asked you to — if you're unsure whether a contact is legitimate, hang up and call the organization back using a number you already know, not one the caller gives you. Treat any unsolicited call, text, or email that cites your personnummer, a recent sick-leave case, or other personal detail and then asks you to "verify" it as a probable scam. Keep an eye on your credit reports and any notifications from Swedish credit bureaus (UC, Bisnode) for a loan or account you didn't open, and consider registering for a kreditupplysningsspärr (credit-check block) with your bank if you're especially concerned. Affected individuals can report suspected fraud to the Swedish Police at polisen.se and raise data-protection concerns with IMY at imy.se; residents elsewhere who receive a suspicious message referencing this breach can report it to their own national data-protection authority or, in the U.S., to the FTC at ReportFraud.ftc.gov.`,
    sourceUrl: "https://www.bleepingcomputer.com/news/security/data-breach-at-major-swedish-software-supplier-impacts-15-million/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Stockholm_City_Hall_2019.jpg?width=1200",
    coverImageCredit: "Photo: Csisc, CC BY-SA 4.0, via Wikimedia Commons — Stockholm City Hall; Stockholm was among the municipalities affected",
    coverImagePosition: 50,
  },
  {
    title: "The Nacogdoches Memorial Hospital Data Breach: How a 226-Bed Texas Hospital Exposed 2.5 Million People's Records",
    slug: "nacogdoches-memorial-hospital-2026-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "nacogdoches-memorial-hospital-2026-data-breach"],
    body: `Nacogdoches Memorial Hospital (NMH), a 226-bed hospital serving a corner of East Texas with a population of roughly 33,000, disclosed in April 2026 that a hacker had gotten into its computer network and potentially made off with files on approximately 2,507,073 people — a number nearly 76 times the size of the city the hospital calls home. The hospital says it first detected the intrusion on January 31, 2026, and a subsequent forensic investigation traced the attacker's initial access back two weeks earlier, to January 15. Notification letters began going out on March 31, and the public disclosure followed on April 1. As of that disclosure, no ransomware or extortion group had publicly claimed responsibility, which is itself unusual — most hospital breaches of this size come with a gang bragging about it on a dark-web leak site, and the silence here means outside researchers have had little independent confirmation of what was actually taken beyond what NMH itself has said.

The scale-to-size mismatch is the first thing worth understanding about this breach. A single community hospital doesn't hold 2.5 million patient records from its own visits — a number that large almost always means the exposed system also stored claims, billing, or referral data covering patients from other providers, insurers, or regional networks that fed information through NMH's systems over the years. NMH has not detailed exactly why its own network held records for a population that large, but the pattern is a familiar one in healthcare breaches: a hospital, lab, or billing system quietly becomes a data repository for far more people than ever walked through its doors, and when it gets hacked, everyone whose information passed through it — not just its own patients — is at risk. According to the hospital's notification letters, the exposed data includes full names, home addresses, phone numbers, email addresses, Social Security numbers, dates of birth, medical record numbers, account numbers, health plan beneficiary numbers, and, for some individuals, full-face photograph images.

What sets this breach apart from many others covered here is what NMH is not offering. The hospital's notification letters do not include a complimentary credit monitoring or identity theft protection service — a benefit that's become close to standard practice after a breach involving Social Security numbers, and one many affected people assume they'll automatically get. NMH's letters instead point affected individuals directly toward the do-it-yourself option: placing a fraud alert or a full security freeze with the three major credit bureaus. That's not a lesser substitute — a credit freeze is free, more effective than most paid monitoring services, and stays in place until you lift it — but it does mean the responsibility for taking that step falls entirely on the person who received the letter, not on any service the hospital signed everyone up for automatically.

A Social Security number and date of birth, paired with a real name and home address, is close to the full kit a criminal needs to open a fraudulent credit account, file a bogus tax return, or pass identity verification at a bank in your name. The exposure of medical record and health plan beneficiary numbers adds a second track: those details can be used for medical identity theft, where someone uses your identity to obtain treatment or equipment, leaving false entries in your own medical record that can affect future care and insurance claims. If your face photograph was among the exposed records, treat that as an added risk factor for identity-verification fraud, since some services increasingly use a photo match as a security check.

If you received a notice from Nacogdoches Memorial Hospital, don't wait for the hospital to act on your behalf — place a security freeze with all three credit bureaus (Equifax, Experian, and TransUnion) yourself; each freeze is free and can be requested online, by phone, or by mail. Request a copy of your medical records and your Explanation of Benefits statements from your health insurer periodically over the next year, and flag anything listing a provider, procedure, or date you don't recognize as possible medical identity theft. Watch for a second wave of scam calls, texts, or emails that reference the breach, NMH, or a "compensation claim" tied to it — a hospital breach reliably draws impersonators hoping people will hand over even more information trying to "protect" themselves. Report suspected identity theft at IdentityTheft.gov, and if you spot a phishing attempt referencing this breach, report it to the FTC at ReportFraud.ftc.gov.`,
    sourceUrl: "https://www.hipaajournal.com/nacogdoches-memorial-hospital-data-breach/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Nacogdoches,_TX,_entrance_sign_IMG_3972.JPG?width=1200",
    coverImageCredit: "Photo: Billy Hathorn, CC BY-SA 3.0, via Wikimedia Commons — a welcome sign at the edge of Nacogdoches, Texas",
    coverImagePosition: 50,
    // representative photo — a city entrance sign, not the hospital building itself; replace with an exact match if found
  },
  {
    title: "The Educational Employees Credit Union Data Breach: How One Compromised Email Account Exposed Members' Social Security Numbers",
    slug: "eecu-educational-employees-credit-union-2026-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "eecu-educational-employees-credit-union-2026-data-breach"],
    body: `Educational Employees Credit Union (EECU), a Fresno-based credit union that serves more than 400,000 members across 12 California counties and bills itself as the largest locally based credit union in the San Joaquin Valley, began notifying members in late May 2026 that a data breach dating back to the previous December had exposed their personal information. EECU says it learned on December 15, 2025 that an unauthorized individual had gained access to a single employee's email account for a limited period. The credit union secured the account and brought in outside cybersecurity investigators, but a full review of what was actually inside that mailbox took months — EECU didn't determine that the exposed emails contained members' sensitive personal information until May 8, 2026, nearly five months after the intrusion was first identified, with notification letters going out roughly three weeks after that.

EECU has not published a total number of affected members, but state breach-notification filings give a partial picture of the reach: at least 949 people in Texas and 34 in Massachusetts were among those notified, meaning the breach reached members well outside EECU's home base in California's Central Valley. The exposed information varies by individual but includes, in different combinations, full names, home addresses, Social Security numbers, driver's license numbers, and financial account information — exactly the combination identity thieves need to open new credit accounts, file fraudulent tax returns, or take out loans in someone else's name.

The mechanism behind this breach is worth pausing on, because it doesn't involve a sophisticated hack of EECU's core banking systems, a ransomware gang, or a vulnerability in any software product — it involves one employee's email inbox. Financial institutions route enormous amounts of sensitive member correspondence, loan documents, and account paperwork through ordinary email over the course of daily business, and a single compromised employee account can sit on months or years of that traffic. That makes routine business email one of the highest-value, lowest-defended targets a bank or credit union has, since it doesn't require defeating encryption or breaching a database — it just requires getting into one person's mailbox, whether through a phishing email, a reused password, or a social-engineering call.

EECU is offering affected members two years of complimentary identity monitoring, credit monitoring, fraud consultation, and identity theft restoration services through Kroll, and the credit union has said it has no evidence so far that the exposed information has actually been used to commit fraud. That's a meaningful offer worth signing up for, but "no evidence yet" is not the same as "safe" — stolen Social Security numbers and driver's license numbers don't expire, and criminals sometimes sit on stolen data for months before using it, which is exactly why EECU's own gap between detecting the intrusion and confirming what was exposed matters: members had no way to protect themselves during the months the credit union was still investigating.

If you're an EECU member, enroll in the free Kroll monitoring services referenced in your notification letter, and independently place a security freeze on your credit reports with Equifax, Experian, and TransUnion — a freeze is free, stronger protection than monitoring alone, and isn't limited to two years. Watch your EECU accounts and any other financial accounts for unfamiliar activity, and keep your breach notification letter along with any related correspondence in case you need it later to document your case. Treat any unexpected call, text, or email that references EECU, your account, or "compensation" for this breach with suspicion — verify by contacting EECU directly through myeecu.org or a phone number from a past statement, never through a link or number provided in the message itself. If you believe your identity has been stolen, report it at IdentityTheft.gov, and report any phishing attempt referencing this breach to the FTC at ReportFraud.ftc.gov.`,
    sourceUrl: "https://thebusinessjournal.com/eecu-data-breach-investigation-member-information-exposed/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Downtown_Fresno_Skyline.jpg?width=1200",
    coverImageCredit: "Photo: JMora24, CC BY-SA 4.0, via Wikimedia Commons — the downtown Fresno, California skyline, home to EECU's headquarters",
    coverImagePosition: 50,
    // representative photo — the city where EECU is headquartered, not a credit union branch; replace with an exact match if found
  },
  {
    title: "The Questel Data Breach: How One Phone Call Compromised a Company Trusted With the World's Unpublished Patents",
    slug: "questel-2026-shinyhunters-vishing-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "questel-2026-data-breach"],
    body: `Questel SAS, a Paris-based intellectual property software and services company that manages patent, trademark, design, and copyright portfolios for more than 20,000 corporate and law-firm clients and roughly 1.5 million users across 30 countries, was hit with an extortion attempt in early August 2026. On August 2, the extortion group ShinyHunters posted a claim on a hacking forum that it had breached Questel and stolen more than 21 million records from the company's Salesforce environment, plus over 147 gigabytes of internal corporate files, and gave the company until August 4 to negotiate before the data would be published.

Questel's own account of what happened differs from ShinyHunters' framing in an important way. The company confirmed that attackers had gained unauthorized access to part of its Microsoft 365 environment — specifically a Sales-related SharePoint site, not the Salesforce platform ShinyHunters described — and said the intrusion followed a vishing (voice phishing) attempt, in which someone impersonated a legitimate employee or IT contact over the phone to talk their way past Questel's own verification and gain access. Vishing has become the signature opening move for this same wave of attacks throughout 2025 and 2026, showing up in breach after breach where the initial compromise had nothing to do with a software flaw and everything to do with a convincing phone call.

When Questel didn't meet ShinyHunters' deadline, the group published the stolen data. Independent researchers who reviewed it found that what actually leaked was corporate contact information tied to Questel's sales leads, support cases, and marketing activity — roughly 1.2 million unique email addresses, along with names, employers, job titles, physical addresses, and phone numbers, which have since been loaded into the breach-notification service Have I Been Pwned. As of this writing, there's no public confirmation that the leak included the actual substance of client patent applications, trademark filings, or other confidential IP records Questel handles day to day; Questel has said it's still conducting a forensic review to determine exactly what was taken and to validate ShinyHunters' broader claims.

Even limited to contact data, this particular list carries an unusual amount of value. Questel's clients are law firms, corporate legal departments, and R&D and innovation teams — the exact people who handle unpublished inventions, pending trademark applications, and other information companies work hard to keep confidential before it's public. A criminal holding real names, real job titles, and real employer information for thousands of in-house patent attorneys and IP managers has a ready-made list for highly targeted phishing: an email that references a real Questel account, a real renewal invoice, or a real pending filing will look completely routine to someone who already receives genuine correspondence from an IP-services vendor, making it a far more convincing lure than a generic phishing blast.

If you or your organization work with Questel, verify any account, renewal, or "security update" notice by contacting Questel directly through questel.com or a phone number and account representative you already have on file — not a link or number in an email referencing this breach. Treat any unexpected call, text, or email that cites your role, employer, or a specific patent or trademark matter as a potential targeted phishing attempt, especially if it asks you to click a link, log in, or share credentials. If your company's IT or legal team uses Questel's platform, ask Questel directly whether any client filing content — not just contact information — was part of what was exposed, and brief in-house counsel and patent staff on the heightened risk of spear-phishing that specifically references real deal or filing details in the weeks ahead. Organizations concerned about the same vishing tactic should make sure help-desk and IT staff verify a caller's identity through an independent channel before resetting a password, adding a multifactor device, or granting system access based on a phone call alone.

Affected individuals in the United States who spot a suspicious message referencing Questel or this breach can report it to the FTC at ReportFraud.ftc.gov. Questel is headquartered in France, and French residents can raise concerns with CNIL, the national data protection authority, at cnil.fr, or report phishing attempts through the government's Cybermalveillance.gouv.fr service.`,
    sourceUrl: "https://cyberinsider.com/questel-confirms-microsoft-365-breach-after-shinyhunters-leaks-data/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/La_D%C3%A9fense_-_Paris_photo5.jpg?width=1200",
    coverImageCredit: "Photo: Sami Mlouhi, CC BY-SA 4.0, via Wikimedia Commons — a Paris business district; Questel is headquartered in Paris",
    coverImagePosition: 50,
    // representative photo — a Paris business district, not Questel's own office; replace with an exact match if found
  },
  {
    title: "The Apollo Global Management Data Breach: How a New Vishing Crew Cracked a $1 Trillion Private Equity Giant",
    slug: "apollo-global-management-2026-vishing-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "apollo-global-management-2026-data-breach"],
    body: `Apollo Global Management, an alternative-asset manager overseeing roughly $1.05 trillion, disclosed on August 21, 2026 that attackers had broken into some of its cloud platforms and stolen personal information belonging to an undisclosed number of people. Apollo says the unauthorized access happened over a specific four-day window, July 6 through July 10, 2026, but the company didn't finish determining that personal data had actually been taken until August 12 — more than a month later — with the public disclosure and a filing with California's attorney general following roughly a week after that. The information exposed included names, dates of birth, home addresses, other contact information, and Social Security numbers; Apollo says it found no evidence as of its disclosure that the stolen data had been posted publicly or used for identity theft or fraud, though "no evidence yet" describes what investigators have found so far, not a guarantee about what happens to the data next.

What makes the Apollo breach worth understanding isn't just its size — it's the method, and the criminal network behind it. Apollo says the intrusion relied on social engineering rather than a software flaw: attackers called employees on their personal cell phones, posed as internal IT help-desk staff, and told them a passkey or FIDO2 security-key enrollment was mandatory and urgent. Employees who went along with the "enrollment" were walked to a fake login page — an adversary-in-the-middle phishing site — that captured their real username, password, and multi-factor authentication code in real time, handing the attackers a live, authenticated session into Apollo's own systems. Researchers at Google's Threat Intelligence Group have linked the campaign to a group tracked as UNC6671, more publicly known by the extortion brand BlackFile, which is itself one of several public names — Redact, Pink, Helix, and Falcon among them — that investigators believe a single core group has used to disguise how much of this activity traces back to one operation, part of the loosely organized, largely English-speaking cybercrime network known as "the Com." Google's researchers say the group collected more than $10 million in Bitcoin ransom payments between January and May 2026 alone.

The choice of target says as much as the technique. BlackFile first emerged in early 2025 hitting retail and hospitality companies, but by July 2026 it had pivoted hard toward an entirely different kind of victim: private equity firms, hedge funds, major law firms, and financial-rating agencies — the institutions that sit on enormous troves of wealthy clients' personal and financial data but, unlike a retailer, rarely think of themselves as a consumer-data breach target. Security researchers have also linked vishing attempts using the same help-desk-impersonation playbook to Blackstone, Bridgewater Associates, Bain Capital, Point72 Asset Management, Millennium Management, Two Sigma, and Citadel, though it remains unclear which of those attempts succeeded in actually compromising systems the way Apollo's did. Apollo appears to be the first of that group to formally confirm that sensitive personal information under its care was taken.

The underlying vulnerability here isn't a firewall or an encryption algorithm — it's the assumption that a caller who already knows an employee's name, department, and internal jargon must be who they say they are. A convincing vishing call doesn't need to defeat multi-factor authentication technically; it just needs to talk a real person into completing an MFA step on the attacker's behalf, which is exactly what a fake "mandatory passkey enrollment" is designed to do. Any organization — financial, legal, medical, or otherwise — that lets employees enroll a new authentication device based on an inbound phone call, rather than requiring the employee to independently verify the request through a channel they initiate themselves, is exposed to the same attack that hit Apollo.

If you're a current or former Apollo employee, an investor, or someone affiliated with an Apollo-managed fund, watch for a notification letter and enroll in the complimentary 24 months of credit monitoring and identity-protection services Apollo is offering through Cyberscout, a TransUnion company. Independently of that offer, place a security freeze on your credit reports with Equifax, Experian, and TransUnion — freezes are free and outlast any two-year monitoring window — since your Social Security number and date of birth were both confirmed exposed. Be skeptical of any future phone call claiming to be Apollo's or your employer's IT help desk asking you to "re-enroll" a passkey, security key, or authenticator app; hang up and call back using a number you already have on file, never one the caller provides. If you work in finance, law, or any organization handling high-net-worth client data, treat this breach as a warning specific to your industry: brief help-desk and IT staff that no security-device enrollment should ever be completed on the basis of an inbound call alone. Anyone who spots a phishing attempt referencing this breach can report it to the FBI's Internet Crime Complaint Center at IC3.gov, and identity theft can be reported at IdentityTheft.gov.`,
    sourceUrl: "https://techcrunch.com/2026/08/21/private-equity-firm-apollo-confirms-data-breach-amid-hacking-wave-targeting-financial-giants/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Manhattan_-_9_West_57th_Street.JPG?width=1200",
    coverImageCredit: "Photo: C.M. de Talleyrand-Périgord, CC BY-SA 4.0, via Wikimedia Commons — 9 West 57th Street in Manhattan, Apollo Global Management's headquarters building",
    coverImagePosition: 50,
  },
  {
    title: "The Berlin City Government Data Breach: How a Seven-Day Gap Let Ransomware Hackers Steal Classified Files and Officials' Passwords",
    slug: "berlin-city-government-2026-rhysida-ransomware-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "berlin-city-government-2026-data-breach"],
    body: `Sometime around August 7, 2026, attackers linked to the ransomware group Rhysida got into the network of Berlin's Senate Department for Mobility, Transport, Climate Protection and the Environment, one of the departments that make up the German capital's city-state government, and began quietly copying files. City officials say the exfiltration continued for roughly five days, through around August 12, before anyone noticed. It then took until August 14 — a full week after the intrusion began — for the affected department to actually be disconnected from Berlin's shared state government network, the Landesnetz, a delay that gave the attackers a wide window to move through connected systems and pull out far more than they otherwise might have. Rhysida publicly claimed the attack on its dark-web leak site on August 28, threatening to publish everything unless paid.

The scale of what Rhysida says it took is substantial for a city government breach: roughly 5.79 terabytes of data spread across about 1.44 million files. According to reporting on the leaked material, it includes government, legal, financial, contractual, HR, and infrastructure records; thousands of names, email addresses, and phone numbers; 148 bank account numbers; personnel files, payroll information, and identity documents belonging to city employees; more than 3,200 nondisclosure agreements; and, most sensitively, plaintext credentials and password-vault data belonging to senior officials, along with what's described as classified or sensitive government material — including records tied to Bundesrat committees and security assessments of critical infrastructure covering Berlin's water supply.

Rhysida demanded 30 bitcoin, worth roughly €2 million at the time, to prevent publication. Berlin's governing mayor, Kai Wegner, said publicly that "Berlin will not give in to blackmail," and the city declined to pay — a decision consistent with the standard law-enforcement guidance that ransom payments fund future attacks without guaranteeing stolen data is actually deleted. Germany's State Criminal Police Office, the public prosecutor's office, and federal security agencies have all opened investigations, and officials confirmed separately that voter and election data were not affected, a point worth noting given that the breach became public roughly three weeks before a Berlin state election. When Berlin refused to pay, Rhysida followed through and published the data it claimed to have stolen.

A breach like this one carries a different kind of risk than a retailer or hospital losing customer records. Alongside the personal data of city employees — the kind that supports routine identity theft and follow-on phishing no matter which organization loses it — this breach reportedly exposed the actual login credentials and password-vault contents of senior government officials, information that can be reused directly to break into other systems those officials have access to, and security assessments of physical infrastructure like a water system, which in the wrong hands is a different category of risk entirely than a stolen email address. The seven-day gap between detecting suspicious activity and actually isolating the affected network is also its own lesson: modern ransomware and data-theft crews often move fast once inside, and the time an organization spends confirming what's happening before disconnecting a compromised network is time attackers spend copying more of it.

If you're a Berlin city employee, or someone who has done business with the Senate Department for Mobility, Transport, Climate Protection and the Environment, watch for official communication from the city about the breach and treat it as your cue to change any password tied to city systems, particularly if you're a senior official whose credentials may have been in the exposed password vaults. Enable multi-factor authentication anywhere it's available on government or personal accounts, since a leaked plaintext password becomes far less useful to an attacker if a second factor is also required. Be alert for a second wave of phishing emails, calls, or texts that reference this breach, a real employee name, or specific details from the leaked files — attackers routinely use authentic-sounding specifics from one breach to make a follow-up scam far more convincing. Berlin residents with questions about their own exposure can contact the Berlin Commissioner for Data Protection and Freedom of Information (Berliner Beauftragte für Datenschutz und Informationsfreiheit) directly rather than through any link in an unsolicited message. Anyone outside Germany who receives a suspicious message referencing this breach can report it to the FTC at ReportFraud.ftc.gov.`,
    sourceUrl: "https://www.bleepingcomputer.com/news/security/berlin-confirms-data-theft-after-rhysida-ransomware-attack-claims/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Berlin_Rotes_Rathaus_B.JPG?width=1200",
    coverImageCredit: "Photo: Zairon, CC0, via Wikimedia Commons — the Rotes Rathaus, seat of Berlin's governing mayor and Senate",
    coverImagePosition: 50,
    // representative photo — Berlin's city hall, not the specific Senate department building that was breached; replace with an exact match if found
  },
  {
    title: "The Thomson Reuters C-Track Breach: How an Attack on Court Software Exposed Sealed Records and Social Security Numbers Across 11 States",
    slug: "thomson-reuters-c-track-court-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "thomson-reuters-c-track-2026-data-breach"],
    sourceUrl: "https://thehackernews.com/2026/09/thomson-reuters-court-software-breach.html",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Thomson_Reuters_building_on_Kennedy_Road.jpg?width=1200",
    coverImageCredit: "Photo: Jason Zhang (Hiàn), CC BY-SA 3.0, via Wikimedia Commons — a Thomson Reuters office building in Toronto",
    coverImagePosition: 50,
    body: `Thomson Reuters disclosed in early September 2026 that an unauthorized party had obtained files from C-Track, a court case management platform sold by its West Publishing Corporation unit — the same Thomson Reuters business behind Westlaw and other legal-research tools. Unlike most breaches covered here, the people at risk never signed up for anything, never clicked a link, and in many cases have never heard of Thomson Reuters at all: C-Track is back-office software that courts themselves run to track criminal and civil cases, which means the exposed data belongs to defendants, plaintiffs, witnesses, and anyone else who has ever had a case move through one of the affected courts.

According to Thomson Reuters, the unauthorized access to C-Track's systems began around March 1, 2026, and continued until West Publishing discovered it on June 30 — nearly four months during which the intruder had a window into the data flowing through the platform. The known affected jurisdictions span 11 U.S. states — Alabama, Pennsylvania, Kentucky, Montana, Nevada, North Dakota, South Carolina, Tennessee, Ohio, New Hampshire, and Wyoming — along with courts in the U.S. Virgin Islands and several courts in Ontario, Canada. Some courts told Thomson Reuters that only backup data was involved; Ohio has said its live production court platform was accessed directly, a distinction that matters because a production system reflects current, active cases rather than an older backup snapshot.

The categories of data at risk are unusually sensitive even by the standards of a major breach: names, Social Security numbers, driver's license numbers, dates of birth, medical information, and health insurance information tied to court filings, plus — in a detail that sets this breach apart — confidential, redacted, or sealed court records at some of the affected courts. A sealed record exists specifically because a judge decided the information inside it shouldn't be public; a juvenile case, a protective order, a victim's identity in a sensitive criminal matter, or medical records submitted as evidence can all end up sealed, and a breach that exposes that material undoes a legal protection a court itself put in place, not just a company's own confidentiality policy.

This is also a clean example of a risk that's easy to overlook: courts, like hospitals and insurers, increasingly run on software built by vendors most of the public never interacts with directly, so a person can do everything right — never use Thomson Reuters, never opt into anything — and still have their Social Security number exposed because of a case that touched a court running C-Track. If you were a party, witness, victim, or juror in a case in any of the affected jurisdictions, or at any point your case record may have lived in a C-Track backup, it's worth treating this breach as potentially relevant to you regardless of whether you receive a formal notice.

Thomson Reuters is offering 12 months of Experian IdentityWorks credit monitoring to individuals it identifies as affected, enrollable with a multi-use code included in its notification letters through the end of 2026, and has set up a dedicated call center at 1-833-918-5294 for questions. If you receive a notice, enroll in the monitoring rather than ignoring it, and because Social Security and driver's license numbers are involved, consider placing a free security freeze on your credit reports with Equifax, Experian, and TransUnion regardless of whether you take the monitoring offer, since a freeze blocks new-account fraud even after monitoring service ends. Treat any unsolicited call, text, or email referencing a specific court case, docket number, or legal matter as a probable follow-up scam rather than a coincidence, especially one that asks you to "verify" a Social Security number or pay a fee to resolve a supposed legal issue — a real court does not initiate contact that way, and this breach hands scammers exactly the authentic case details that make such a call sound convincing. Anyone who believes a sealed or otherwise confidential record involving them may have been exposed should contact the specific court that handled their case directly, using a phone number looked up independently rather than one provided in any message about the breach, and anyone who suspects their identity has already been misused can start a recovery plan at IdentityTheft.gov and report it to the FTC at ReportFraud.ftc.gov.`,
  },
  {
    title: "The Motility Software Solutions Breach: How a Hack of RV, Boat, and Powersports Dealership Software Exposed 766,000 Buyers' Social Security Numbers",
    slug: "motility-software-solutions-2025-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "motility-software-solutions-2025-data-breach"],
    sourceUrl: "https://www.securityweek.com/766000-impacted-by-data-breach-at-dealership-software-provider-motility/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Alliance_Coach_RV_Sales.JPG?width=1200",
    coverImageCredit: "Photo: Michael Rivera (Mjrmtg), CC BY-SA 3.0, via Wikimedia Commons — an RV dealership lot, the kind of business that runs on Motility's software",
    coverImagePosition: 50,
    // representative photo — a different RV dealership, not Motility's own customer, since Motility is a software vendor rather than a storefront; replace with an exact match if found
    body: `Motility Software Solutions isn't a name most car, RV, boat, or motorcycle buyers have ever heard, which is exactly the point of what happened to it. Motility is a subsidiary of the auto-industry giant Reynolds and Reynolds and makes dealer management software — the back-office system roughly 7,000 dealerships nationwide, concentrated heavily in RV, marine, and powersports sales, use to run sales, financing, service, and customer records. When Motility's own systems were hit by ransomware, it wasn't a single dealership's data at risk; it was the shared back-end of thousands of them at once.

Motility says the attack occurred on August 19, 2025, and it disclosed the breach roughly six weeks later, on October 1, 2025, after completing its investigation into what the intruders had accessed. Security researchers have attributed the intrusion to a group calling itself the "Pear gang," which used privilege escalation and exploitation of remote services to move through Motility's network before encrypting files with RSA-2048 and posting stolen data online. In total, Motility says 766,000 people had personal information exposed — names, home addresses, email addresses, phone numbers, dates of birth, Social Security numbers, and driver's license numbers.

The reach of a breach like this is easy to underestimate because of how invisible dealer management software normally is. Someone who bought a travel trailer, a pontoon boat, or a side-by-side ATV from a dealership that used Motility's platform has no reason to remember the software's name, and many affected customers likely learned about Motility for the first time only when a breach notification letter arrived. That gap between "who actually holds my data" and "who I actually did business with" is a recurring theme across software-vendor breaches, and it means a notice from an unfamiliar company name shouldn't be dismissed as spam just because the recipient doesn't recognize it.

Because full Social Security numbers and driver's license numbers were exposed, together with a real name, address, and date of birth, this breach hands criminals essentially everything needed to open a fraudulent credit account, file a false tax return, or pass a basic identity check at another institution — a materially more serious combination than an exposed email or password alone. Motility offered affected individuals a year of complimentary identity monitoring, with enrollment that ran through December 19, 2025; the company also agreed to a $4,949,500 class-action settlement, which received preliminary court approval in April 2026, to resolve claims that it failed to adequately protect the data in its care.

If you bought or serviced an RV, boat, motorcycle, or other powersports vehicle from a dealership at any point and received a notice from Motility, don't dismiss it because the name is unfamiliar — the connection runs through your dealership's back-office software, not through any account you set up yourself. Because Social Security and driver's license numbers were involved, place a free security freeze on your credit reports with Equifax, Experian, and TransUnion, which blocks new accounts from being opened in your name and remains in effect even after any identity-monitoring offer expires. Watch your credit reports and any Explanation of Benefits or IRS correspondence for signs of new-account fraud or a fraudulent tax filing, and treat any unsolicited call, text, or email that references a real vehicle purchase, dealership, or loan as a possible follow-up scam rather than routine business — verify it by calling the dealership directly using a number you look up yourself. If your identity has already been misused, report it and get a personalized recovery plan at IdentityTheft.gov, and file a complaint with the FTC at ReportFraud.ftc.gov.`,
  },
  {
    title: "The Baylor Genetics Data Breach: How a Hack of a DNA Testing Lab Exposed 2.8 Million People's Genetic and Medical Data",
    slug: "baylor-genetics-2026-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "baylor-genetics-2026-data-breach"],
    sourceUrl: "https://www.hipaajournal.com/baylor-genetics-data-breach/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Baylor_College_of_Medicine,_Houston,_Texas.jpg?width=1200",
    coverImageCredit: "Photo: Zereshk, public domain, via Wikimedia Commons — a Baylor College of Medicine building in Houston's Texas Medical Center",
    coverImagePosition: 50,
    // representative photo — a Baylor College of Medicine building; Baylor Genetics is an affiliated clinical lab, not shown to be housed in this specific building
    body: `Baylor Genetics, a Houston-based clinical laboratory affiliated with Baylor College of Medicine that runs genetic and molecular diagnostic testing ordered by physicians nationwide — everything from prenatal screening to inherited-cancer-risk panels to rare-disease workups for children — detected suspicious activity in its computer network on June 15, 2026. An investigation later determined that an unauthorized party had actually been inside the network for several days before that, between June 11 and June 17, and it took until July 30 for the lab to finish reviewing exactly whose information had been exposed. Notification letters describing the incident began going out roughly a month later, in late August and early September 2026.

The final number is stark: Baylor Genetics reported that 2,810,878 people had personal information exposed, a total that spans both patients whose samples the lab processed on behalf of their own doctors and current or former Baylor Genetics employees. State-level breach filings give a sense of just how far beyond Texas that reach extended — roughly 250,000 Texas residents, about 57,000 Massachusetts residents, and several thousand Vermont residents were named in separate state notifications, meaning patients whose only connection to Baylor Genetics was a single lab requisition form filled out by an out-of-state doctor's office were caught up in the breach along with the lab's own local patient base. According to the company, the exposed data varies by individual but can include full names, dates of birth, medical and genetic testing information, laboratory results, health insurance details, and — for a more limited subset of those affected — Social Security numbers.

What makes a breach at a clinical genetics lab different from a breach at a typical hospital or insurer is the specific category of information at stake. A genetic test result isn't like a blood-pressure reading that changes month to month — it's a permanent, unchangeable record of an inherited condition, a cancer-risk mutation, or a rare disease diagnosis that a patient may not have even fully processed with their own doctor yet, let alone be ready to have exposed. Unlike a stolen password or even a Social Security number, a genetic result can't be reset or reissued, and because DNA is inherently shared, a breach involving someone's genetic data can carry implications for their parents, children, and siblings even though none of those relatives ever used Baylor Genetics themselves. As of this writing, no ransomware or extortion group has publicly claimed responsibility for the intrusion, which means there's been little independent outside confirmation of exactly how the attackers got in or what they did with the data once they had it — patients are left largely relying on the lab's own account of the incident.

Baylor Genetics is offering affected individuals 24 months of complimentary credit monitoring and identity protection through IDX, enrollable at app.idx.us using the code printed in each notification letter, or by calling IDX directly at 1-866-200-0985; as of this writing, the enrollment window is open through November 14, 2026, so don't let a letter sit unopened past that date. If your notice indicates your Social Security number was exposed, go a step further than the free monitoring and place a security freeze on your credit reports with Equifax, Experian, and TransUnion — a freeze is free, stronger protection than monitoring alone, and stays in place until you lift it yourself. Because this breach touched genetic and health information rather than just financial data, also review your health insurance Explanation of Benefits statements for any test or procedure you don't recognize, which can be a sign of medical identity theft. Treat any unsolicited call, text, or email referencing Baylor Genetics, a genetic test you took, or a "compensation claim" tied to this breach with real suspicion — verify anything by calling the lab or your ordering physician's office directly using a number you look up yourself, never one provided in the message. Anyone who suspects their identity has already been misused can start a recovery plan at IdentityTheft.gov, and phishing attempts referencing this breach can be reported to the FTC at ReportFraud.ftc.gov.`,
  },
  {
    title: "The Ledger Data Breach: How a Hacked Shipping Partner Put Crypto Wallet Owners' Home Addresses at Risk Again",
    slug: "ledger-global-e-2026-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "ledger-global-e-2026-data-breach"],
    sourceUrl: "https://www.bleepingcomputer.com/news/security/ledger-customers-impacted-by-third-party-global-e-data-breach/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Ledger_Nano_S_-_Hard_Wallet_-_Cold_Storage_for_Cryptocurrency_04.jpg?width=1200",
    coverImageCredit: "Photo: Motokoka, CC BY-SA 4.0, via Wikimedia Commons — a Ledger Nano S hardware wallet",
    coverImagePosition: 50,
    body: `Ledger, the French manufacturer of the Nano S and Nano X hardware wallets used by millions of cryptocurrency holders to store their private keys offline, told customers on January 5, 2026 that Global-e — the third-party company Ledger uses as the merchant of record to process and ship international orders placed on Ledger.com — had suffered its own data breach, and that some Ledger customer order information had been caught up in it. According to Ledger's notice, the exposed data included customers' names, contact details, and shipping addresses tied to international orders. Ledger was emphatic that no passwords, no 24-word recovery phrases, and no cryptocurrency itself were ever at risk, since Ledger's wallets are self-custodial and Global-e never had access to that information in the first place — the company's core security promise held. The number of customers affected has not been publicly disclosed.

That reassurance about the wallets themselves is true and worth taking seriously, but it undersells why a breach exposing nothing but a name and a home address is still a serious problem specifically for Ledger customers, because of what happened the last time this exact scenario played out. In June 2020, hackers breached Ledger's own e-commerce and marketing database directly, exposing roughly 1.1 million email addresses and, for about 272,000 customers, full names, phone numbers, and physical mailing addresses — a list that was later dumped publicly online for anyone to download. The fallout wasn't limited to phishing emails: security researchers and Ledger customers themselves documented a wave of threatening letters, extortion attempts, and in a number of well-publicized cases, home invasions and armed robberies targeting people whose addresses had been on that list, on the theory that anyone who owns a Ledger hardware wallet is likely to be holding meaningful cryptocurrency value. Security researcher Jameson Lopp, who has tracked violent crypto-related crimes since 2020, has recorded more than 200 such incidents worldwide, with cases roughly doubling in 2025 — a trend researchers refer to bluntly as the "$5 wrench attack," where a criminal skips trying to hack a wallet at all and instead uses coercion or violence in person to make an owner hand over access directly.

That history is exactly what makes the new Global-e breach worth taking seriously even though the leaked data looks, on paper, like "just" a name and an address. For most companies, a breach limited to contact information is a relatively low-stakes incident; for a hardware wallet maker's customer list, a home address is a targeting list for the small subset of criminals willing to escalate from phishing to physical confrontation, because it answers the one question those criminals can't get from a blockchain explorer alone — where a specific, likely-wealthy crypto holder actually lives. Ledger's own customers began reporting a fresh round of phishing emails and texts referencing real order details within days of the January disclosure, following the same pattern seen after the 2020 breach: messages designed to look like official Ledger support, warning of a security issue and pushing recipients toward a fake "Ledger Live" update or a page asking them to type in their recovery phrase to "verify" their wallet.

If you've ever ordered a Ledger product, especially through an international shipment that Global-e would have processed, treat any email, text, or call referencing your Ledger order, account, or a security issue with serious skepticism — Ledger will never ask for your 24-word recovery phrase under any circumstances, through any channel, for any reason, and typing it into a website is the single action that empties a wallet fastest. Go directly to ledger.com or open the Ledger Live app yourself rather than clicking any link in an unsolicited message. Because a real home address may now be circulating in a criminal marketplace, take the physical-security angle seriously as well: consider using a P.O. box or a different delivery address for any future cryptocurrency-related purchases, be cautious about publicly discussing crypto holdings or displaying wallet-related merchandise, and if you receive any threatening contact or believe you're being targeted for your holdings specifically, contact local law enforcement and the FBI's Internet Crime Complaint Center at IC3.gov rather than handling it alone. Suspected phishing referencing this breach can also be reported to the FTC at ReportFraud.ftc.gov.`,
  },  {
    title: "The Dropbox-Lenovo Account Breach: How Attackers Logged Into Strangers' Accounts Without Ever Knowing a Password",
    slug: "dropbox-lenovo-id-2026-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "dropbox-lenovo-id-2026-breach"],
    sourceUrl: "https://www.bleepingcomputer.com/news/security/dropbox-accounts-breached-through-lenovo-email-verification-flaw/",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Dropbox_(7463062672).jpg?width=1200",
    coverImageCredit: "Photo: Ian Lamont (IN 30 MINUTES Guides), CC BY 2.0, via Wikimedia Commons — the Dropbox app",
    coverImagePosition: 50,
    body: `Between August 4 and August 21, 2026, an unknown number of attackers logged into roughly 5,000 Dropbox accounts without ever entering a password, guessing a password, or tricking anyone into handing one over. They didn't need to. The attackers exploited a flaw in "Sign in with Lenovo ID" — the "Continue with SSO" option Dropbox offers alongside a regular email-and-password login — that let anyone register a brand-new Lenovo ID using someone else's email address without Lenovo actually verifying that the person registering owned that inbox. Once an attacker controlled a Lenovo ID tied to a victim's email, Dropbox's login system trusted that Lenovo account as proof of identity and let them straight into the matching Dropbox account, no password required. Dropbox has said the intruder viewed and downloaded files from a portion of the roughly 5,000 accounts affected, though it hasn't disclosed exactly how many. Lenovo, for its part, said the flaw involved "a legacy integration between Lenovo ID and Dropbox" and that its own customers' accounts were not directly compromised by it.

What makes this incident worth understanding — even if you've never touched a Dropbox account with a Lenovo login — is what it exposes about how "Sign in with X" buttons actually work. Every time a website offers to let you log in with your Google, Apple, Microsoft, or Lenovo account instead of a dedicated password, that site is agreeing to trust the other company's word that you are who you say you are. That arrangement, called federated login or single sign-on, is usually a genuine security upgrade — it means one fewer password to reuse or leak. But it also means the security of your Dropbox account (or any account using this pattern) becomes only as strong as the weakest identity-verification step anywhere in that chain, including at a company you've never interacted with and have no relationship with at all. Some affected Dropbox users only learned anything was wrong because their login screen started unexpectedly offering a "Continue with SSO" option tied to a Lenovo ID they never created — a strange, easy-to-miss signal that something in the background had already been tampered with.

Dropbox responded by forcibly expiring every session that had been authenticated through a Lenovo ID and adding a new requirement that anyone using Lenovo ID authentication must also enter their actual Dropbox password, closing the specific gap the attackers used. If you use Dropbox — with or without a Lenovo login — change your Dropbox password now, use a unique password you don't reuse anywhere else, and turn on two-step verification in Dropbox's security settings, since that adds a second, independent barrier that a compromised SSO login alone can't get past. Check your Dropbox account's "connected apps" and login-activity pages for any sign-in location, device, or session you don't recognize, and review shared links and recently accessed files for anything you didn't touch yourself. More broadly, treat any unexpected new sign-in option appearing on a login screen you use regularly as a red flag worth investigating rather than a convenience worth ignoring, and be cautious of any follow-up email or text claiming to be from Dropbox or Lenovo that asks you to "verify" your account by clicking a link — go directly to dropbox.com yourself instead. If you believe your account was accessed without permission, you can report it to the FTC at ReportFraud.ftc.gov.`,
  },
  {
    title: "The Weverse Data Breach: How a Payment API Flaw Exposed More Than 420,000 K-Pop Fans' Purchase Records",
    slug: "weverse-hybe-2026-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "weverse-hybe-2026-data-breach"],
    sourceUrl: "https://www.koreajoongangdaily.com/korea/weverse-data-leak-affects-420000-users/12862760",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Seoul-Yongsan.gu-01.jpg?width=1200",
    coverImageCredit: "Photo: m-louis, CC BY-SA 2.0, via Wikimedia Commons — Yongsan-gu, Seoul, the district where Weverse's parent company HYBE is headquartered",
    coverImagePosition: 50,
    // representative photo — a general view of the Yongsan district of Seoul, not the specific HYBE or Weverse office building
    body: `Weverse, the fan community and merchandise app built by HYBE Corporation — the entertainment company behind BTS, Le Sserafim, Enhypen, and dozens of other K-pop acts — disclosed on September 6, 2026 that a security vulnerability had exposed personal data tied to 422,584 user accounts. An outside tipster first flagged the flaw to the Korea Internet & Security Agency (KISA) on September 3, and Weverse says it locked down the vulnerability within days of being notified. The company traced the problem to an application programming interface (API) used to process payment information, which an outside party was able to query without proper authorization.

The exposed data was narrower than in many breaches of this size but still sensitive: internal account identifiers, along with purchase details including payment method type, transaction currency and amount, purchase and refund dates, and order status. Weverse says the leak did not include user names, phone numbers, email addresses, passwords, or complete card numbers, and that the specific fields exposed make direct payment forgery or unauthorized transfers unlikely using this data alone. That distinction matters, but it undersells why the breach is still worth fans' attention: Weverse isn't just a chat app for BTS and other HYBE acts, it's the primary storefront where a global fanbase — heavily weighted toward the United States, Latin America, Japan, and Southeast Asia — buys albums, merchandise, and paid content, and purchase history on the platform can double as an entry list for "fansign" lottery events, where the number of albums a fan has bought affects their odds of winning a video call or in-person meeting with an artist. A leak touching purchase amounts and timing, even without a name attached, is exactly the kind of detail a scammer could pair with other information to make a follow-up phishing message feel credible.

HYBE Weverse Company CEO Yang Joo-il issued a formal apology to users on the night of September 6, and the company says it has restricted access to the vulnerable API, removed the exposed internal identifiers, and committed to auditing all of its externally accessible APIs going forward. If you have a Weverse account, change your password and enable two-factor authentication if you haven't already, and review your linked payment methods and recent purchase or subscription history for anything you don't recognize. Because transaction details were exposed, treat any message claiming to be from Weverse about a "refund," "payment issue," or "order verification" with real suspicion in the weeks ahead — log into the app or go to weverse.io directly rather than clicking a link in an email or text, and never enter a card number, password, or one-time code into a page you reached through an unsolicited message. Suspected phishing referencing this breach can be reported to the FTC at ReportFraud.ftc.gov, and international fans can also check their own country's consumer-protection agency for local reporting options.`,
  },
  {
    title: "The Ryde Data Breach: What 4.5 Million Nordic E-Scooter Customers Should Know",
    slug: "ryde-nordic-2026-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "ryde-nordic-2026-data-breach"],
    sourceUrl: "https://cybernews.com/security/ryde-customer-data-stolen/",
    body: `Ryde Technology AS, the electric scooter- and moped-sharing service operating across Norway, Sweden, Finland, and Germany, disclosed a data breach after discovering unauthorized access to its systems overnight between August 1 and 2, 2026. The company says it blocked the intrusion once it was detected, but by then an attacker had already obtained data from every active customer account — roughly 4.5 million in total. Ryde is a distinct company from other operators using similar names elsewhere in the world, including a Singapore-based ride-hailing app; this breach affected only the Nordic and German e-scooter service.

According to Ryde's own breach notice, the exposed information includes phone numbers, email addresses, dates of birth, partial payment card numbers — specifically the first six and last four digits, a format sometimes used for identity checks — and payment histories. For a smaller subset of users, unverified names and addresses were also involved. Ryde says full card numbers were never affected, since it doesn't store them directly; those are held by its separate payment processor. The company has also said no ride-history or location data was taken, meaning attackers do not appear to have a record of where individual customers have traveled. As of Ryde's initial disclosure, the company said the full scope of the incident was still under investigation.

Even without a full card number or ride history in the mix, this combination of data is useful to a scammer in a specific way: a real name, phone number, date of birth, and partial card number is enough to make an impersonation attempt sound convincing. A caller or texter who already knows your phone number, birthday, and the last four digits of the card on your Ryde account can use those details to seem like a legitimate representative of the company — and then ask you to "confirm" the rest of the card number, a password, or a one-time verification code to finish "securing" your account. That request is the scam; a company that already has your account details never needs you to read the sensitive remainder back to it.

If you have a Ryde account, there's no need to cancel your payment card, since Ryde says full numbers weren't exposed and the affected digits alone can't be used to make a charge. It's still worth changing your Ryde app password and reviewing your account's recent ride and payment activity for anything unfamiliar. Be skeptical of any unsolicited call, text, or email that references your Ryde account, a recent ride, or a "security update" and then asks you to click a link, share a password, or read back a verification code — go directly to the Ryde app or ryde-technology.com instead of responding. Norwegian residents can report suspicious contact to the Norwegian Data Protection Authority (Datatilsynet) or Kripos's National Cyber Crime Center; U.S. residents who receive a similar message can report it to the FTC at ReportFraud.ftc.gov.`,
  },
  {
    title: "The Baydöner Data Breach: How Plaintext Passwords Exposed 1.3 Million Turkish Restaurant Customers",
    slug: "baydoner-2026-data-breach-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "baydoner-2026-data-breach"],
    sourceUrl: "https://haveibeenpwned.com/Breach/Baydoner",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/D%C3%B6ner_kebab_in_Ankara,_Turkey.jpg?width=1200",
    coverImageCredit: "Photo: E4024, CC BY-SA 4.0, via Wikimedia Commons — a döner kebab restaurant in Ankara, Turkey",
    coverImagePosition: 50,
    // representative photo — a generic döner kebab restaurant in Turkey, not a Baydöner location specifically
    body: `Baydöner, a well-known Turkish restaurant and döner kebab chain, had its customer database posted to a hacking forum in March 2026, exposing records tied to roughly 1.3 million unique email addresses. Turkey's data protection authority, the Personal Data Protection Authority (KVKK), later investigated and traced the intrusion back to compromised login credentials belonging to a company employee, which attackers used to get into Baydöner's information systems. In early September 2026, KVKK announced the results of that investigation along with a formal fine against the chain.

What makes this breach unusually serious is not just its size but what was actually stored in plain view. Alongside names, phone numbers, cities of residence, dates of birth, and genders, the leaked database included roughly 622,000 customer passwords stored in plaintext — meaning they were never scrambled with encryption or hashing in the first place, so anyone who obtained the database could read them directly, no cracking required. A smaller number of records also included Turkish national ID numbers and purchase history tied to the chain's loyalty program. Baydöner has said payment and financial data were not affected, and KVKK's investigation reportedly traced part of the incident back to a security lapse at a third-party vendor from as early as August 2025. Regulators fined the company for failing to maintain adequate data security measures and for gaps in how it notified those affected.

Plaintext password storage matters well beyond Baydöner's own app, because of one of the most common security mistakes people make: reusing the same password across multiple accounts. If you had a Baydöner account and used that same password anywhere else — a banking app, an email account, another delivery or loyalty app — a criminal who now has that exact password in readable form can simply try it on those other accounts, a technique called credential stuffing that succeeds far more often than most people expect. The same is true for the exposed national ID numbers, which in Turkey function similarly to a Social Security number in the U.S. and can be used to attempt identity theft or fraudulent account openings.

If you have ever had a Baydöner account, change that password immediately, and — more importantly — change it anywhere else you may have reused it, prioritizing your email and banking logins first since those are the highest-value targets. Use a unique password for every account going forward, ideally generated and stored by a password manager, so a breach at any one company can't cascade into others. Watch for phishing messages that reference your name, phone number, or past Baydöner orders to appear more credible, and never respond to a text or call asking you to "verify" your national ID number or a one-time code. Turkish consumers can check whether their information was exposed and file complaints through KVKK at kvkk.gov.tr; those elsewhere who reused a Baydöner password can check exposure at a service like Have I Been Pwned and should still change any reused credentials as a precaution.`,
  },
  {
    title: "Hurricane Melissa Relief Scams: How Fraudsters Exploited a Real Disaster in Real Time",
    slug: "hurricane-melissa-relief-scams-guide",
    author: "ScamShield Editorial",
    tags: ["guide", "hurricane-melissa-relief-scams"],
    sourceUrl: "https://www.netcraft.com/blog/hurricane-melissa-jamaica-relief-scams",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Hurricane_Melissa_at_landfall_true_color.png?width=1200",
    coverImageCredit: "NASA (public domain) — satellite image of Hurricane Melissa at landfall in Jamaica, October 2025",
    coverImagePosition: 50,
    body: `Hurricane Melissa made landfall in Jamaica at the end of October 2025 as a catastrophic Category 5 storm, one of the strongest hurricanes ever recorded to hit the island, devastating homes, the power grid, and infrastructure across large stretches of the country. Within hours of the first news coverage, fraud researchers and Jamaica's own Cyber Incident Response Team (Ja-CIRT) began documenting a wave of fake donation websites built to intercept the money people wanted to send to help.

Netcraft, a cybersecurity firm that tracks online fraud, identified at least 14 fraudulent domains built around the disaster in the days that followed, including sites like "donate.melissarelieffundtojamaicans.online," "jamaicahurricanerelief.com," "melissareliefjamaica.com," and "supportjamaicagovjm.com" — names deliberately chosen to sound official or to mimic government and established charity branding. Jamaica's Cyber Incident Response Team separately flagged more than two dozen fraudulent relief websites in an official public warning, urging donors to give only through verified government and established charity channels. Some of these fake sites cloned the visual design and text of real humanitarian organizations wholesale, making them difficult to distinguish from the real thing at a glance. Investigators also found scammers using AI-generated images and video to make fabricated damage photos and "victim" appeals feel more emotionally urgent and convincing.

One tactic worth understanding specifically: several fraudulent sites displayed a static QR code linked to a cryptocurrency wallet address, rather than a normal payment form. Scammers favor cryptocurrency for exactly this reason — once a donation is sent, the transaction can't be reversed or clawed back the way a credit card chargeback can, and the wallet itself offers no way to verify who controls it or whether any of the money will reach Jamaica at all. A wallet address with no visible history of legitimate transaction activity, sitting behind a QR code on a donation page, is a strong warning sign on its own.

This pattern repeats after essentially every major disaster — hurricanes, wildfires, earthquakes — because scammers know that people's instinct to help outpaces their instinct to verify. Before donating to any disaster relief effort, go directly to a charity's known web address by typing it yourself rather than clicking a link from an email, text, or social media post, and check the organization's standing through an independent evaluator like the BBB Wise Giving Alliance or Charity Navigator. Favor donation methods that offer some recourse, such as a credit card, over methods that don't, including wire transfers, gift cards, or cryptocurrency. Be skeptical of newly registered domains, generic "relief fund" names not tied to a specific known organization, and any appeal that pressures you to give immediately without giving you time to check it out. If you spot a suspicious disaster-relief solicitation, you can report it to the FTC at ReportFraud.ftc.gov; Jamaican residents can report directly to Ja-CIRT through the Office of the Prime Minister's website.`,
  },
];
