import { SeedStateAgSource } from './types';

// Every state (plus DC)'s Attorney General consumer protection office —
// each URL independently verified live before inclusion. Most state AGs
// take scam complaints but don't publish a structured report the way
// FTC/CFPB do; has_published_reports + reports_url mark the ones that do
// (a press-release archive, a consumer-alerts page with real content, or
// an actual annual report), rather than treating every state as equal.
export const SEED_STATE_AG_SOURCES: SeedStateAgSource[] = [
  {
    state: 'AL',
    state_name: 'Alabama',
    agency_name: 'Alabama Attorney General\'s Office — Consumer Interest Division',
    consumer_protection_url: 'https://www.alabamaag.gov/divisions/consumer-interest-division/',
    reports_url: 'https://www.alabamaag.gov/category/press-release/',
    has_published_reports: true,
    description: 'Mediates consumer complaints and runs scam-education outreach; its general press-release archive periodically includes real consumer scam alerts alongside broader office news.',
  },
  {
    state: 'AK',
    state_name: 'Alaska',
    agency_name: 'Alaska Department of Law — Consumer Protection Unit',
    consumer_protection_url: 'https://www.law.alaska.gov/department/civil/consumer/cpindex.html',
    reports_url: 'https://law.alaska.gov/department/civil/consumer/cp-headlines-archive.html',
    has_published_reports: true,
    description: 'Investigates unfair and deceptive practices, mediates complaints, and registers telemarketers and charities; its headlines archive carries real dated settlement and consumer-alert entries.',
  },
  {
    state: 'AZ',
    state_name: 'Arizona',
    agency_name: 'Arizona Attorney General\'s Office — Consumer Protection & Advocacy',
    consumer_protection_url: 'https://www.azag.gov/consumer',
    reports_url: 'https://www.azag.gov/media/press-releases',
    has_published_reports: true,
    description: 'Investigates consumer fraud and enforces the Arizona Consumer Fraud Act; its press-release archive is real and actively updated, mixing scam alerts with major settlement announcements.',
  },
  {
    state: 'AR',
    state_name: 'Arkansas',
    agency_name: 'Arkansas Attorney General\'s Office — Consumer Protection Division',
    consumer_protection_url: 'https://arkansasag.gov/divisions/public-protection/consumer-protection/',
    reports_url: 'https://arkansasag.gov/news-alerts/news-releases/',
    has_published_reports: true,
    description: 'Mediates consumer transaction disputes and enforces the Deceptive Trade Practices Act; its news archive includes recurring dated "Consumer Alert" posts on specific active scams.',
  },
  {
    state: 'CA',
    state_name: 'California',
    agency_name: 'California Department of Justice — Office of the Attorney General, Consumer Protection Section',
    consumer_protection_url: 'https://oag.ca.gov/consumers',
    reports_url: 'https://oag.ca.gov/new-press-categories/consumer-protection',
    has_published_reports: true,
    description: 'Investigates and prosecutes false advertising and unfair or fraudulent business practices; its consumer-protection press category is a substantive, actively updated archive of real dated releases.',
  },
  {
    state: 'CO',
    state_name: 'Colorado',
    agency_name: 'Colorado Department of Law — Office of the Attorney General, Consumer Protection Section',
    consumer_protection_url: 'https://coag.gov/office-sections/consumer-protection/',
    reports_url: 'https://coag.gov/category/press-releases/',
    has_published_reports: true,
    description: 'Investigates and prosecutes violations of the Colorado Consumer Protection Act and handles consumer mediation via StopFraudColorado.gov; a large, actively maintained press-release archive backs it up.',
  },
  {
    state: 'CT',
    state_name: 'Connecticut',
    agency_name: 'Connecticut Office of the Attorney General — Consumer Protection Section',
    consumer_protection_url: 'https://portal.ct.gov/ag/sections/consumer-protection',
    reports_url: 'https://portal.ct.gov/ag/press-releases',
    has_published_reports: true,
    description: 'Investigates and litigates unfair or deceptive trade practices under CUTPA; the office\'s press-release archive, organized back to 2010, carries real dated consumer-relevant content.',
  },
  {
    state: 'DE',
    state_name: 'Delaware',
    agency_name: 'Delaware Department of Justice — Fraud and Consumer Protection Division, Consumer Protection Unit',
    consumer_protection_url: 'https://attorneygeneral.delaware.gov/fraud/cpu/',
    reports_url: 'https://news.delaware.gov/category/justice/prs/fraud/',
    has_published_reports: true,
    description: 'Enforces two dozen-plus consumer statutes covering fraud, deceptive trade, privacy, and telemarketing; the state\'s central news portal carries the office\'s real, dated fraud-related releases.',
  },
  {
    state: 'DC',
    state_name: 'District of Columbia',
    agency_name: 'Office of the Attorney General for the District of Columbia — Office of Consumer Protection',
    consumer_protection_url: 'https://oag.dc.gov/consumer-protection',
    reports_url: 'https://oag.dc.gov/taxonomy/term/63',
    has_published_reports: true,
    description: 'Investigates deceptive and unfair business and landlord practices and runs free consumer and tenant mediation; its dedicated Consumer Alerts archive is frequent and current, alongside an annual Impact Report.',
  },
  {
    state: 'FL',
    state_name: 'Florida',
    agency_name: 'Florida Office of the Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://www.myfloridalegal.com/consumer-protection',
    reports_url: 'https://www.myfloridalegal.com/consumer-protection/consumer-alerts',
    has_published_reports: true,
    description: 'Enforces Florida\'s Deceptive and Unfair Trade Practices Act; its Consumer Alerts archive is a real, actively populated feed on specific scams, not a static tips page.',
  },
  {
    state: 'GA',
    state_name: 'Georgia',
    agency_name: 'Georgia Department of Law — Consumer Protection Division',
    consumer_protection_url: 'https://consumer.georgia.gov/',
    reports_url: 'https://consumer.georgia.gov/news-alerts',
    has_published_reports: true,
    description: 'Investigates consumer complaints and enforces Georgia\'s Fair Business Practices Act and Lemon Law; its news archive is actively updated with real dated settlement and recovery announcements.',
  },
  {
    state: 'HI',
    state_name: 'Hawaii',
    agency_name: 'Hawaii Department of Commerce and Consumer Affairs — Office of Consumer Protection',
    consumer_protection_url: 'https://cca.hawaii.gov/ocp/',
    reports_url: 'https://cca.hawaii.gov/ocp/notices/security-breach/',
    has_published_reports: true,
    description: 'Sits under the state Department of Commerce and Consumer Affairs rather than the AG\'s office; investigates deceptive trade and telemarketing complaints and maintains a real, ongoing data-breach notice log.',
  },
  {
    state: 'ID',
    state_name: 'Idaho',
    agency_name: 'Idaho Office of the Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://www.ag.idaho.gov/consumer-protection/',
    reports_url: 'https://www.ag.idaho.gov/consumer-protection/alerts/',
    has_published_reports: true,
    description: 'Enforces Idaho\'s Consumer Protection Act, Telephone Solicitation Act, and Charitable Solicitation Act; its Consumer Alerts page is a real, actively updated feed with dated, specific scam warnings.',
  },
  {
    state: 'IL',
    state_name: 'Illinois',
    agency_name: 'Office of the Illinois Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://illinoisattorneygeneral.gov/consumer-protection/',
    reports_url: 'https://illinoisattorneygeneral.gov/news-room/',
    has_published_reports: true,
    description: 'Handles complaints on purchases, identity theft, home repair, and health care; its press-release archive is large and actively updated, including specific dated scam alerts.',
  },
  {
    state: 'IN',
    state_name: 'Indiana',
    agency_name: 'Indiana Office of the Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://www.in.gov/attorneygeneral/consumer-protection-division/',
    reports_url: 'https://www.in.gov/attorneygeneral/newsroom/',
    has_published_reports: true,
    description: 'Mediates and investigates consumer complaints and enforces Indiana\'s Deceptive Consumer Sales Act; its Newsroom maintains real year-by-year press-release archives covering scam alerts and enforcement news.',
  },
  {
    state: 'IA',
    state_name: 'Iowa',
    agency_name: 'Iowa Office of the Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://www.iowaattorneygeneral.gov/about-us/divisions/consumer-protection',
    reports_url: 'https://www.iowaattorneygeneral.gov/newsroom',
    has_published_reports: true,
    description: 'Protects consumers from fraud, deception, and unfair sales practices; its Newsroom is a large, actively updated archive with recurring scam-specific alerts (imposter scams, jury-duty scams, tax scams).',
  },
  {
    state: 'KS',
    state_name: 'Kansas',
    agency_name: 'Office of the Kansas Attorney General — Public Protection Division, Consumer Protection',
    consumer_protection_url: 'https://www.ag.ks.gov/divisions/public-protection/consumer-protection',
    reports_url: 'https://www.ag.ks.gov/media-center/news-releases',
    has_published_reports: true,
    description: 'Educates consumers and businesses and sues over deceptive practices; the office publishes dated consumer alerts, though its site blocks automated verification and this entry relies on independently cross-referenced search results rather than a direct fetch.',
  },
  {
    state: 'KY',
    state_name: 'Kentucky',
    agency_name: 'Kentucky Office of the Attorney General — Office of Consumer Protection',
    consumer_protection_url: 'https://www.ag.ky.gov/about/Office-Divisions/OCP/Pages/default.aspx',
    reports_url: 'https://www.ag.ky.gov/Resources/Consumer-Resources/Consumers/Pages/Current%20Consumer%20Alerts.aspx',
    has_published_reports: true,
    description: 'Enforces the Kentucky Consumer Protection Act through three subdivisions; its Current Consumer Alerts page has genuine substantive scam content, though the page appears not to have been updated recently.',
  },
  {
    state: 'LA',
    state_name: 'Louisiana',
    agency_name: 'Louisiana Department of Justice — Public Protection Division',
    consumer_protection_url: 'https://ag.louisiana.gov/Division/PublicProtection',
    reports_url: 'https://ag.louisiana.gov/News',
    has_published_reports: true,
    description: 'Handles consumer disputes, unfair trade practices, and data-breach notification; its News archive carries real dated press releases including consumer-protection enforcement actions.',
  },
  {
    state: 'ME',
    state_name: 'Maine',
    agency_name: 'Office of the Maine Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://www.maine.gov/ag/consumer/',
    reports_url: 'https://www.maine.gov/ag/news-and-library/consumer-scam-notices-and-alerts',
    has_published_reports: true,
    description: 'Enforces the Unfair Trade Practices Act and runs a free Consumer Mediation Service and Lemon Law arbitration; its alerts page has real, dated advisory entries on current scam patterns.',
  },
  {
    state: 'MD',
    state_name: 'Maryland',
    agency_name: 'Office of the Attorney General of Maryland — Consumer Protection Division',
    consumer_protection_url: 'https://oag.maryland.gov/our-office/Pages/consumer-protection-division.aspx',
    reports_url: 'https://oag.maryland.gov/our-office/Documents/pdfs/OAG%20Annual%20Report%202025.pdf',
    has_published_reports: true,
    description: 'Provides mediation and binding arbitration for consumer complaints against businesses and health insurers; publishes a genuine annual report, though its live consumer-alerts search tool is JavaScript-driven and couldn\'t be independently confirmed.',
  },
  {
    state: 'MA',
    state_name: 'Massachusetts',
    agency_name: 'Massachusetts Attorney General\'s Office — Consumer Advocacy & Response Division',
    consumer_protection_url: 'https://www.mass.gov/get-consumer-support',
    reports_url: 'https://www.mass.gov/orgs/office-of-the-attorney-general/news',
    has_published_reports: true,
    description: 'Mediates consumer complaints and funds a statewide network of local consumer programs; publishes a substantive annual Consumer Advocacy Report with hotline volume, settlement totals, and top complaint categories.',
  },
  {
    state: 'MI',
    state_name: 'Michigan',
    agency_name: 'Michigan Department of Attorney General — Consumer Protection Team',
    consumer_protection_url: 'https://www.michigan.gov/consumerprotection',
    reports_url: 'https://www.michigan.gov/ag/news',
    has_published_reports: true,
    description: 'Handles roughly 10,000-plus consumer complaints a year through a dedicated consumer-protection site; the general AG news page carries real dated consumer-relevant releases.',
  },
  {
    state: 'MN',
    state_name: 'Minnesota',
    agency_name: 'Office of the Minnesota Attorney General — Consumer Protection',
    consumer_protection_url: 'https://www.ag.state.mn.us/consumer/',
    reports_url: 'https://www.ag.state.mn.us/Office/Communications.asp',
    has_published_reports: true,
    description: 'Mediates consumer complaints covering false advertising, debt collection, and deceptive practices, and publishes real, dated consumer alerts through its communications page.',
  },
  {
    state: 'MS',
    state_name: 'Mississippi',
    agency_name: 'Mississippi Attorney General\'s Office — Consumer Protection Division',
    consumer_protection_url: 'https://attorneygenerallynnfitch.com/divisions/consumer-protection/',
    reports_url: 'https://attorneygenerallynnfitch.com/media/press-releases/',
    has_published_reports: true,
    description: 'Handles consumer complaints and robocall/telemarketing and solicitor-registration enforcement; its press-release archive carries recurring, real dated scam warnings (holiday scams, government-imposter scams).',
  },
  {
    state: 'MO',
    state_name: 'Missouri',
    agency_name: 'Missouri Attorney General\'s Office — Consumer Protection Section',
    consumer_protection_url: 'https://ago.mo.gov/divisions/consumer/',
    reports_url: 'https://ago.mo.gov/press-releases/',
    has_published_reports: true,
    description: 'Enforces antitrust, securities, telemarketing, and charitable-trust laws; its press-release archive carries frequent, real dated scam warnings tied to seasonal patterns.',
  },
  {
    state: 'MT',
    state_name: 'Montana',
    agency_name: 'Montana Department of Justice — Office of Consumer Protection',
    consumer_protection_url: 'https://dojmt.gov/office-of-consumer-protection',
    reports_url: 'https://dojmt.gov/tag/ocp/',
    has_published_reports: true,
    description: 'Investigates deceptive trade practices and distributes scam-education materials, publishing an annual figure for consumer dollars saved; the office\'s site blocks automated verification, so this entry relies on independently cross-referenced search results rather than a direct fetch.',
  },
  {
    state: 'NE',
    state_name: 'Nebraska',
    agency_name: 'Nebraska Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://protectthegoodlife.nebraska.gov/',
    reports_url: 'https://protectthegoodlife.nebraska.gov/consumer-news',
    has_published_reports: true,
    description: 'Enforces state and federal laws against deceptive business practices and handles ID theft reports and data-breach notices; its Consumer News page carries real dated releases, mostly legal-action announcements.',
  },
  {
    state: 'NV',
    state_name: 'Nevada',
    agency_name: 'Office of the Nevada Attorney General — Bureau of Consumer Protection',
    consumer_protection_url: 'https://ag.nv.gov/Hot_Topics/Citizen/Consumer_Protection/',
    reports_url: 'https://ag.nv.gov/News/Press_Releases/',
    has_published_reports: true,
    description: 'Files lawsuits and enforces deceptive-trade and antitrust laws on behalf of consumers; its press-release page carries real dated alerts on active scams alongside enforcement news.',
  },
  {
    state: 'NH',
    state_name: 'New Hampshire',
    agency_name: 'New Hampshire Department of Justice — Consumer Protection and Antitrust Bureau',
    consumer_protection_url: 'https://www.doj.nh.gov/citizens/consumer-protection-antitrust-bureau',
    reports_url: 'https://www.doj.nh.gov/news-and-media',
    has_published_reports: true,
    description: 'Enforces unfair and deceptive-practices laws and investigates elder financial exploitation, regularly issuing dated "Consumer Alert" releases; the office\'s site blocks automated verification, so this entry relies on independently cross-referenced search results rather than a direct fetch.',
  },
  {
    state: 'NJ',
    state_name: 'New Jersey',
    agency_name: 'New Jersey Division of Consumer Affairs',
    consumer_protection_url: 'https://www.njoag.gov/programs/consumer-protection/',
    reports_url: 'https://www.njoag.gov/category/division/division-of-consumer-affairs/',
    has_published_reports: true,
    description: 'A "state-level CFPB" enforcing the NJ Consumer Fraud Act, covering fraud, robocalls, student-loan protection, and investor protection; its news archive carries real dated enforcement and settlement releases.',
  },
  {
    state: 'NM',
    state_name: 'New Mexico',
    agency_name: 'New Mexico Department of Justice — Consumer Affairs',
    consumer_protection_url: 'https://nmdoj.gov/about-the-office/consumer-affairs/',
    reports_url: 'https://nmdoj.gov/press-release/',
    has_published_reports: true,
    description: 'Tracks complaints, offers dispute mediation, and investigates suspicious business activity, regularly publishing dated "Scam Alert" releases; the office\'s site blocks automated verification, so this entry relies on independently cross-referenced search results rather than a direct fetch.',
  },
  {
    state: 'NY',
    state_name: 'New York',
    agency_name: 'New York Attorney General — Consumer Frauds and Protection Bureau',
    consumer_protection_url: 'https://ag.ny.gov/resources/individuals/consumer-issues',
    reports_url: 'https://ag.ny.gov/press-releases',
    has_published_reports: true,
    description: 'Prosecutes fraudulent and deceptive trade practices and mediates thousands of consumer complaints a year; a large, filterable press-release archive going back to 2019 and periodic special reports back it up.',
  },
  {
    state: 'NC',
    state_name: 'North Carolina',
    agency_name: 'North Carolina Department of Justice — Consumer Protection Division',
    consumer_protection_url: 'https://ncdoj.gov/protecting-consumers/',
    reports_url: 'https://ncdoj.gov/newsroom/',
    has_published_reports: true,
    description: 'Helps residents resolve complaints and recover money from scams via a dedicated hotline, regularly publishing dated "Consumer Alert" posts; the office\'s site is behind an automated bot-check that blocked direct verification, so this entry relies on independently cross-referenced search results.',
  },
  {
    state: 'ND',
    state_name: 'North Dakota',
    agency_name: 'North Dakota Attorney General — Consumer Protection and Antitrust Division',
    consumer_protection_url: 'https://attorneygeneral.nd.gov/consumer-resources/',
    reports_url: 'https://attorneygeneral.nd.gov/news/',
    has_published_reports: true,
    description: 'Enforces consumer-fraud and antitrust laws and runs a voluntary complaint-mediation program; real consumer-relevant alerts appear occasionally within the office\'s general news feed rather than a dedicated alerts section.',
  },
  {
    state: 'OH',
    state_name: 'Ohio',
    agency_name: 'Ohio Attorney General — Consumer Protection Section',
    consumer_protection_url: 'https://www.ohioattorneygeneral.gov/consumers',
    reports_url: 'https://www.ohioattorneygeneral.gov/consumeradvocate',
    has_published_reports: true,
    description: 'A one-stop resource for consumer complaints, enforcing 25-plus Ohio consumer-protection laws; its "Consumer Advocate" newsletter is a substantial, actively maintained archive dating back to 2011 with bi-monthly dated posts.',
  },
  {
    state: 'OK',
    state_name: 'Oklahoma',
    agency_name: 'Oklahoma Attorney General — Consumer Protection Unit',
    consumer_protection_url: 'https://oklahoma.gov/oag/about/divisions/cpu.html',
    reports_url: 'https://oklahoma.gov/oag/news/newsroom.html',
    has_published_reports: true,
    description: 'Mediates consumer complaints and runs the Telemarketer Restriction Act (Do Not Call) registry; the AG\'s newsroom publishes real dated press releases with specific scam alerts.',
  },
  {
    state: 'OR',
    state_name: 'Oregon',
    agency_name: 'Oregon Department of Justice — Consumer Protection Section',
    consumer_protection_url: 'https://www.doj.state.or.us/consumer-protection/',
    reports_url: 'https://www.doj.state.or.us/media-home/news-media-releases/category/consumer-protection/',
    has_published_reports: true,
    description: 'Runs a Consumer Hotline, a Scam Alert Network email subscription, and a public complaints database, publishing an annual "Top 10 Consumer Complaints" report and dated press releases.',
  },
  {
    state: 'PA',
    state_name: 'Pennsylvania',
    agency_name: 'Pennsylvania Office of Attorney General — Bureau of Consumer Protection',
    consumer_protection_url: 'https://www.attorneygeneral.gov/public-protection-division/bureau-consumer-protection/',
    reports_url: 'https://www.attorneygeneral.gov/taking-action/',
    has_published_reports: true,
    description: 'Mediates consumer complaints and brings enforcement actions under the state Consumer Protection Law through six regional offices; its news archive carries real, frequent dated consumer-alert content.',
  },
  {
    state: 'RI',
    state_name: 'Rhode Island',
    agency_name: 'Rhode Island Office of the Attorney General — Consumer Protection Unit',
    consumer_protection_url: 'https://riag.ri.gov/consumerprotection',
    reports_url: 'https://riag.ri.gov/press-releases',
    has_published_reports: true,
    description: 'Mediates consumer complaints against businesses and files enforcement actions; its press-release archive carries real dated consumer-protection settlements and lawsuits.',
  },
  {
    state: 'SC',
    state_name: 'South Carolina',
    agency_name: 'South Carolina Attorney General — Consumer Protection & Antitrust Division',
    consumer_protection_url: 'https://www.scag.gov/inside-the-office/legal-services-division/consumer-protection-antitrust/',
    has_published_reports: false,
    description: 'Enforces the SC Unfair Trade Practices Act through lawsuits, but explicitly does not handle individual consumer complaints — those go to the separate SC Department of Consumer Affairs — and publishes no dedicated alerts archive of its own.',
  },
  {
    state: 'SD',
    state_name: 'South Dakota',
    agency_name: 'South Dakota Division of Consumer Protection',
    consumer_protection_url: 'https://consumer.sd.gov/whoweare.aspx',
    reports_url: 'https://consumer.sd.gov/consumeralerts.aspx',
    has_published_reports: true,
    description: 'Staffed by an Assistant Attorney General and investigators, though hosted on a separate consumer-focused domain; its alerts page carries real dated content on active scams, including specific dollar-loss figures.',
  },
  {
    state: 'TN',
    state_name: 'Tennessee',
    agency_name: 'Tennessee Attorney General\'s Office — Division of Consumer Affairs',
    consumer_protection_url: 'https://www.tn.gov/attorneygeneral/working-for-tennessee/consumer-affairs.html',
    reports_url: 'https://www.tn.gov/attorneygeneral/news.consumer-affairs.html',
    has_published_reports: true,
    description: 'Tennessee\'s clearinghouse for consumer complaints, mediating disputes and recovering millions for consumers annually; its news archive carries real dated seasonal scam alerts and enforcement actions.',
  },
  {
    state: 'TX',
    state_name: 'Texas',
    agency_name: 'Texas Office of the Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://www.texasattorneygeneral.gov/consumer-protection',
    reports_url: 'https://www.texasattorneygeneral.gov/news/categories/consumer-protectionscams',
    has_published_reports: true,
    description: 'Accepts complaints and enforces the Deceptive Trade Practices Act; its news category carries real, dated consumer alerts and enforcement actions, including government-impersonation warnings and pyramid-scheme judgments.',
  },
  {
    state: 'UT',
    state_name: 'Utah',
    agency_name: 'Utah Attorney General\'s Office — Commercial Enforcement Division',
    consumer_protection_url: 'https://attorneygeneral.utah.gov/commercial-enforcement/',
    has_published_reports: false,
    description: 'Focuses on multistate investigations and settlements rather than day-to-day complaints — those go to the separate Utah Division of Consumer Protection — and its own consumer-tagged content is stale, mostly dating to 2020.',
  },
  {
    state: 'VT',
    state_name: 'Vermont',
    agency_name: 'Office of the Vermont Attorney General — Consumer Protection Unit',
    consumer_protection_url: 'https://ago.vermont.gov/attorney-generals-office-divisions-and-units/consumer-protection',
    reports_url: 'https://ago.vermont.gov/blog/category/press-releases',
    has_published_reports: true,
    description: 'Investigates consumer fraud, enforces Vermont\'s Consumer Protection Act, and mediates complaints jointly with the University of Vermont; publishes a current press archive and an annual "Top Ten Consumer Complaints" report.',
  },
  {
    state: 'VA',
    state_name: 'Virginia',
    agency_name: 'Office of the Attorney General of Virginia — Consumer Protection Section',
    consumer_protection_url: 'https://www.oag.state.va.us/consumer-protection/',
    reports_url: 'https://www.oag.state.va.us/media-center/news-releases',
    has_published_reports: true,
    description: 'Protects Virginians from fraud, deception, and illegal marketplace practices and runs a Consumer Protection Hotline; its News Releases archive is real and current, spanning multiple pages.',
  },
  {
    state: 'WA',
    state_name: 'Washington',
    agency_name: 'Washington State Office of the Attorney General — Consumer Protection Division',
    consumer_protection_url: 'https://www.atg.wa.gov/consumer-protection',
    reports_url: 'https://www.atg.wa.gov/scam-alerts',
    has_published_reports: true,
    description: 'Enforces the Washington Consumer Protection Act and runs the Consumer Resource Center, returning millions to consumers a year; its Scam Alerts page is real and actively maintained with dated entries.',
  },
  {
    state: 'WV',
    state_name: 'West Virginia',
    agency_name: 'Office of the WV Attorney General — Consumer Protection and Antitrust Division',
    consumer_protection_url: 'https://ago.wv.gov/consumer-protection-and-antitrust-division',
    reports_url: 'https://ago.wv.gov/consumer-protection/latest-scams',
    has_published_reports: true,
    description: 'Handles complaints on deceptive sales, warranty violations, and identity theft; its "Latest Scams" page and linked monthly "Top Scams Reported" articles provide real, recurring dated content.',
  },
  {
    state: 'WI',
    state_name: 'Wisconsin',
    agency_name: 'Wisconsin Department of Justice — Public Protection Unit',
    consumer_protection_url: 'https://www.wisdoj.gov/Pages/PublicSafety/protecting-consumers.aspx',
    reports_url: 'https://www.wisdoj.gov/Pages/AboutUs/press-releases.aspx',
    has_published_reports: true,
    description: 'Litigates consumer-protection cases referred by other state agencies rather than fielding complaints directly; its general press-release archive includes real, dated consumer and elder-fraud enforcement actions.',
  },
  {
    state: 'WY',
    state_name: 'Wyoming',
    agency_name: 'Wyoming Attorney General\'s Office — Consumer Protection and Antitrust Unit',
    consumer_protection_url: 'https://attorneygeneral.wyo.gov/law-office-division/consumer-protection-and-antitrust-unit',
    reports_url: 'https://attorneygeneral.wyo.gov/law-office-division/consumer-protection-and-antitrust-unit/resolved-matters',
    has_published_reports: true,
    description: 'Enforces the Wyoming Consumer Protection Act, accepts written complaints, and participates in multistate enforcement actions; both its current-alerts page and its resolved-matters archive carry real, dated content.',
  },
];
