// What photo each photoless profile should get, and what the photo shows.
//
// For a Madoff or a Ponzi there is a famous mug shot in the public domain.
// For almost everyone here there is no free photo of the person at all, and
// there is no honest way to manufacture one. What does exist is a real photo
// of the place or the thing the case turns on: the port where P&R's containers
// were supposed to sit, the glacier Sextant valued its fund on, the Christchurch
// earthquake payouts BlackfortFX went after.
//
// So every entry carries a `caption` describing what the photo actually
// depicts, which is stored in coverImageCredit and rendered beneath the image.
// That caption is not decoration - it is the thing that stops a reader taking
// a photo of a courthouse for a photo of the defendant. Write it as a plain
// statement of what is in the frame and how it relates to the case, never as
// something that could be read as a portrait.
//
// `query` searches Commons; `file` names one exact file instead, for cases
// where a search ranks the wrong thing first. Either way the licence is read
// off the file's own page before anything is written, and a case with no
// verifiable free photo simply keeps its abstract art.

export interface PhotoPlanEntry {
  slug: string;
  /** Commons search terms. Ignored when `file` is set. */
  query?: string;
  /** An exact Commons file name, without the "File:" prefix. */
  file?: string;
  /** What the photo shows, and how it relates to the case. */
  caption: string;
  /** Vertical focal point 0-100. Skylines and buildings usually want a lower number. */
  position?: number;
}

export const PHOTO_PLAN: PhotoPlanEntry[] = [
  { slug: 'bernhard-eugen-fritsch-starclub-fugitive-fraud', query: 'Santa Monica California city', caption: 'Santa Monica, California, where StarClub was based', position: 45 },
  { slug: 'manjit-singh-bedi-snap-benefits-fraud-fugitive', query: 'Tacoma Washington downtown', caption: 'Tacoma, Washington, where the store was authorised to accept SNAP benefits', position: 45 },
  { slug: 'darren-anthony-robinson-qyu-holdings-ponzi-fugitive', query: 'Panama City Panama skyline', caption: 'Panama City — QYU told investors it operated from Panama and the Cayman Islands', position: 45 },
  { slug: 'christopher-w-burns-dynamic-money-fugitive-fraud', query: 'Atlanta Georgia skyline', caption: 'Atlanta, where Burns built his profile as an adviser and radio host', position: 45 },
  { slug: 'darryl-cohen-nba-players-life-settlement-fraud', query: 'basketball arena NBA game', caption: 'Cohen’s advisory clients were professional basketball players', position: 50 },
  { slug: 'francisco-javier-sarabia-bonanza-global-solutions-fraud', query: 'United States Securities and Exchange Commission headquarters', caption: 'The SEC headquarters in Washington, D.C. The agency brought the civil case', position: 45 },
  { slug: 'eduardo-hernandez-free-riding-brokerage-scheme', query: 'stock market trading screen monitor', caption: 'The scheme exploited an instant-deposit credit feature on a retail brokerage', position: 50 },
  { slug: 'chris-isis-terry-im-mastery-academy-fraud', query: 'Federal Trade Commission building Washington', caption: 'The Federal Trade Commission, which brought the civil case', position: 45 },
  { slug: 'amit-ahuja-kapil-gulati-priyanshu-walia-tech-support-fraud', query: 'Baltimore Maryland courthouse', caption: 'Baltimore, where the federal grand jury returned the indictment', position: 45 },
  { slug: 'charles-lawrence-landes-prive-investment-fraud', query: 'Stockholm Sweden city', caption: 'Stockholm — the trust Lawrence built his pitch around was supposedly Swedish', position: 45 },
  { slug: 'christian-rasmus-mikkelsen-publishing-com-earnings-fraud', query: 'self publishing books shelf', caption: 'Publishing.com sold coaching on self-publishing as an income stream', position: 50 },
  { slug: 'doxo-steve-shivers-roger-parks-bill-pay-junk-fees', query: 'utility bill paperwork', caption: 'Doxo charged fees to pay bills consumers could pay free at the biller', position: 50 },
  { slug: 'cangialosi-girgis-sarabella-max-infinity-pre-ipo-fraud', query: 'New York Stock Exchange building facade', caption: 'The scheme sold shares in companies it claimed were about to go public', position: 45 },
  { slug: 'craig-allen-cheetah-fund-fraud', query: 'Atlanta Georgia downtown buildings', caption: 'Atlanta, where C.M. Allen Capital Management operated', position: 45 },
  { slug: 'dilip-bose-ritika-mohit-arora-tech-support-scam', query: 'Texas State Capitol Austin', caption: 'Austin — the Texas Attorney General brought the action that shut the ring down', position: 40 },
  { slug: 'bernard-mcbride-tutela-mining-gold-fraud', query: 'gold mine California historic', caption: 'A California gold mine. Tutela Mining claimed to own a working one', position: 50 },
  { slug: 'eric-levitt-gulf-coast-settlements-promissory-note-fraud', query: 'Fort Myers Florida', caption: 'Fort Myers, Florida, where Gulf Coast Settlements was based', position: 45 },
  { slug: 'blueprint-to-wealth-ftc-business-opportunity-scheme', query: 'Federal Trade Commission headquarters building', caption: 'The Federal Trade Commission, which brought the case', position: 45 },
  { slug: 'bruno-crastes-h2o-asset-management-windhorst-bonds', query: 'City of London financial district skyline', caption: 'The City of London, where H2O Asset Management was based', position: 45 },
  { slug: 'stewart-ford-keydata-death-bonds-fraud', query: 'Canary Wharf London financial district', caption: 'Canary Wharf, London. Keydata sold its bonds to ordinary savers through independent advisers', position: 45 },
  { slug: 'guy-flintham-unauthorised-investment-scheme-fraud', query: 'Preston Law Courts Lancashire', caption: 'Preston Law Courts, Lancashire, where the case was heard', position: 45 },
  { slug: 'rodney-forrest-platinum-asset-management-insider-trading', query: 'Sydney Australia skyline harbour', caption: 'Sydney, where Forrest took the information from an unattended office', position: 45 },
  { slug: 'beaufort-securities-fbi-pump-and-dump-sting', query: 'City of London office buildings', caption: 'London, where Beaufort Securities was authorised and based', position: 45 },
  { slug: 'jorg-biehl-infinus-group-ponzi-scheme', query: 'Dresden Germany city', caption: 'Dresden, where the Infinus Group was headquartered', position: 45 },
  { slug: 'bill-papas-forum-finance-bank-fraud', query: 'Sydney Australia central business district', caption: 'Sydney, where Forum Finance was based', position: 45 },
  { slug: 'first-guardian-shield-master-fund-collapse', query: 'Melbourne Australia skyline', caption: 'Melbourne, where many of the advisers involved were based', position: 45 },
  { slug: 'cbex-crypto-bridge-exchange-nigeria-collapse', query: 'Lagos Nigeria skyline', caption: 'Lagos — CBEX drew Nigerian investors before collapsing in 2025', position: 45 },
  { slug: 'arck-llp-richard-clay-kathryn-clark-fraud', query: 'Nottingham England city centre', caption: 'Nottingham, where Arck LLP was run from', position: 45 },
  { slug: 'capital-merchant-finance-nicholls-douglas-tallentire', query: 'Auckland New Zealand skyline', caption: 'New Zealand, where the finance company took debentures from the public', position: 45 },
  { slug: 'five-star-consumer-finance-kirk-macdonald-bowden', query: 'Wellington New Zealand harbour city', caption: 'New Zealand, where Five Star took deposits from ordinary savers', position: 45 },
  { slug: 'david-ames-harlequin-group-caribbean-resort-fraud', query: 'Saint Vincent Grenadines beach resort', caption: 'A Caribbean resort beach of the kind Harlequin sold to British savers off-plan', position: 50 },
  { slug: 'anthony-constantinou-cwm-fx-forex-ponzi-fugitive', query: 'Heron Tower Bishopsgate London', caption: 'Heron Tower on Bishopsgate, where CWM’s London office was', position: 40 },
  { slug: 'balsam-ag-procedo-export-financing-fraud', query: 'artificial turf sports field', caption: 'Synthetic sports flooring — Balsam AG was the world’s largest maker', position: 50 },
  { slug: 'mikheil-biniashvili-milton-group-pumats-scam-software', query: 'call centre office workstations', caption: 'A call centre floor of the kind the Milton Group ran its boiler rooms from', position: 50 },
  { slug: 'philip-galles-tyche-asset-management-ponzi', query: 'Chicago Board of Trade Building', caption: 'Chicago, where Galles claimed to run a commodities trading firm', position: 40 },
  { slug: 'john-julieanne-dimitrion-mortgage-alliance-fugitive-fraud', query: 'Honolulu Hawaii city', caption: 'Honolulu, where Mortgage Alliance targeted homeowners facing foreclosure', position: 45 },
  { slug: 'john-sterling-myers-sterling-capital-fraud', query: 'United States Securities and Exchange Commission seal building', caption: 'The SEC, which pursued the case against Sterling Capital', position: 45 },
  { slug: 'khalid-satary-medicare-genetic-testing-fraud', query: 'DNA laboratory genetic testing equipment', caption: 'Genetic testing labs billed Medicare $547 million for tests patients never needed', position: 50 },
  { slug: 'monica-cannon-grant-violence-in-boston-nonprofit-fraud', query: 'Boston Massachusetts skyline', caption: 'Boston, where Violence in Boston operated as an anti-violence charity', position: 45 },
  { slug: 'nelson-holdo-phantom-rolex-fraud', query: 'Rolex wristwatch luxury watches', caption: 'The scheme traded on watches that were never delivered', position: 50 },
  { slug: 'david-gilchrist-christopher-novinger-texas-tax-lien-ponzi-scheme', query: 'Dallas Texas skyline', caption: 'Texas, where the tax lien scheme was sold to investors', position: 45 },
  { slug: 'linh-le-trong-luu-inventis-ventures-fraud', query: 'Little Saigon Westminster California', caption: 'Southern California’s Vietnamese community, which the scheme was sold through', position: 50 },
  { slug: 'john-boston-verona-elder-financial-exploitation', query: 'elderly person hands care', caption: 'The case turned on a power of attorney over a 90-year-old client', position: 50 },
  { slug: 'jose-bello-gator-lending-ponzi-scheme', query: 'Miami Florida skyline', caption: 'Florida, where "Gator Lending" was promoted on Facebook and Discord', position: 45 },
  { slug: 'ian-gregory-bell-denver-day-trading-fraud', query: 'Denver Colorado skyline mountains', caption: 'Denver, where Bell pitched himself to professional athletes as a day trader', position: 45 },
  { slug: 'joseph-lewis-tavistock-insider-trading-fraud', query: 'Manhattan federal courthouse Foley Square', caption: 'The Manhattan federal court where the insider-trading case was brought', position: 40 },
  { slug: 'john-won-tae-hung-kang-forexnpower-fraud', query: 'Los Angeles California skyline', caption: 'Los Angeles, where ForexNPower solicited investors', position: 45 },
  { slug: 'middle-class-united-cooperative-investment-fraud', query: 'Securities and Exchange Commission building Washington DC', caption: 'The SEC, which brought the action over the $500 "memberships"', position: 45 },
  { slug: 'geoffrey-auyeung-oil-storage-money-laundering', query: 'oil storage tank terminal', caption: 'An oil storage terminal. The deal the 81 bank accounts were opened for did not exist', position: 50 },
  { slug: 'jingliang-su-cambodia-crypto-scam-laundering', query: 'Phnom Penh Cambodia city', caption: 'Phnom Penh — the laundering pipeline for stolen crypto ran through Cambodia', position: 45 },
  { slug: 'joshua-allen-michael-cox-ferrum-capital-ponzi-scheme', query: 'promissory note financial document', caption: 'Ferrum Capital sold notes its promoters said were effectively risk-free', position: 50 },
  { slug: 'joey-stanton-dodson-citadel-energy-ponzi-scheme', query: 'oil drilling rig North Dakota', caption: 'Oilfield water-treatment ventures were the pitch behind Citadel Energy', position: 50 },
  { slug: 'marco-santarelli-norada-capital-ponzi-scheme', query: 'residential rental houses suburb', caption: 'Norada marketed turnkey rental property investment before the notes failed', position: 50 },
  { slug: 'greensky-predatory-home-improvement-loan-settlement', query: 'Consumer Financial Protection Bureau building', caption: 'The CFPB, which brought the action over loans taken out in customers\u2019 names', position: 45 },
  { slug: 'genneva-gold-malaysia-buyback-scheme', query: 'gold bullion bars', caption: 'Gold bullion. Genneva sold it with a buyback promise it could not fund', position: 50 },
  { slug: 'kent-whitney-church-for-the-healthy-self-ponzi-scheme', query: 'church interior pews empty', caption: 'The scheme was run through an entity registered as a church', position: 50 },
  { slug: 'mohammed-mansoor-khan-ima-halal-ponzi-scheme', query: 'Bangalore India city', caption: 'Bangalore, where IMA sold its "halal" investment scheme', position: 45 },
  { slug: 'lex-greensill-supply-chain-finance-collapse', query: 'London financial district Canary Wharf', caption: 'London, where Greensill Capital was headquartered', position: 45 },
  { slug: 'michael-king-mfs-premium-income-fund-fraud', query: 'Gold Coast Queensland Australia', caption: 'Queensland, where MFS was based before the raid on its fund', position: 45 },
  { slug: 'manuel-fernandez-de-sousa-pescanova-accounting-fraud', query: 'fishing trawler fleet harbour Spain', caption: 'Pescanova\u2019s fishing business was real; \u20ac2 billion of its debt was hidden', position: 50 },
  { slug: 'peter-kambolin-systematic-alpha-cherry-picking-fraud', query: 'Miami Beach Florida skyline', caption: 'Miami, where Systematic Alpha Management was based', position: 45 },
  { slug: 'francius-marganda-easy-transfer-global-transfer-ponzi', query: 'money transfer remittance counter', caption: 'The scheme was sold as funding international money-transfer loan programs', position: 50 },
  { slug: 'david-mcwilliams-alammc-disability-housing-fraud', query: 'wheelchair accessible housing ramp', caption: 'The fund was raised to build specialist disability accommodation', position: 50 },
  { slug: 'james-mawhinney-mayfair-101-fraud', query: 'Dunk Island Queensland', caption: 'Dunk Island, centrepiece of the "tourism mecca" Mayfair 101 pitched', position: 50 },
  { slug: 'dozy-mmobuosi-tingo-group-fraud', query: 'Lagos Nigeria city street', caption: 'Nigeria, where Tingo claimed a vast agricultural fintech operation', position: 45 },
  { slug: 'maxwell-odum-mba-forex-ponzi-scheme', query: 'Abuja Nigeria city', caption: 'Nigeria, where MBA Forex took deposits before vanishing overnight', position: 45 },
  { slug: 'arif-patel-faisaltex-carousel-fraud', query: 'Preston Lancashire England', caption: 'Preston, where Faisaltex operated at the centre of the carousel fraud', position: 45 },
  { slug: 'kubus-scheme-adriaan-nieuwoudt-milk-pyramid', query: 'milk bottles dairy', caption: 'The "activator" culture at the centre of the Kubus scheme was grown in milk', position: 50 },
  { slug: 'raymond-jones-sterling-group-retiree-housing-collapse', query: 'retirement home apartment building', caption: 'Seniors paid for "rent-free" leases in housing that was repossessed', position: 50 },
  { slug: 'ben-jayaweera-growth-plus-abalone-fund-fraud', query: 'abalone shellfish aquaculture', caption: 'An abalone farm — the single asset Jayaweera called a diversified fund', position: 50 },
  { slug: 'mark-mccabe-guevara-capital-forex-fraud', query: 'Commodity Futures Trading Commission building', caption: 'The CFTC, which brought the action over accounts that did not exist', position: 45 },
  { slug: 'getfinancial-ring-cybertrading-fraud-germany', query: 'Berlin Germany skyline', caption: 'Germany, where the fake cybertrading network solicited investors', position: 45 },
  { slug: 'stephane-gagnon-unlock-my-rsp-fraud', query: 'Montreal Quebec skyline', caption: 'Quebec, where the "Unlock My RSP" scheme targeted locked-in retirement savings', position: 45 },
  { slug: 'gary-booth-steven-nicholas-connaught-income-fund-tiuta', query: 'Financial Conduct Authority Stratford London', caption: 'The UK regulator, whose case followed the Connaught fund collapse', position: 45 },
  { slug: 'karl-suleman-cash-resource-australia-trolley-ponzi', query: 'shopping trolleys supermarket car park', caption: 'Suleman\u2019s real business was collecting supermarket trolleys', position: 50 },
  { slug: 'mark-bryers-blue-chip-collapse-australia-tax-fraud', query: 'Auckland New Zealand city buildings', caption: 'New Zealand, where the Blue Chip property scheme collapsed', position: 45 },
  { slug: 'nickolas-karantzis-isignthis-asx-disclosure-fraud', query: 'Australian Securities Exchange Sydney', caption: 'The ASX, to which iSignthis failed to make required disclosures', position: 45 },
  { slug: 'songeziwe-mbalo-bhaca-green-forex-ponzi-fsca', query: 'Johannesburg South Africa skyline', caption: 'South Africa, where the FSCA found Bhaca Green had never traded', position: 45 },
  { slug: 'john-robert-leake-nfl-linebacker-ponzi-scheme', query: 'American football stadium', caption: 'Leake played professional football before selling fake investments', position: 50 },
  { slug: 'william-brent-meikle-hit-tv-brands-fraud', query: 'television studio camera production', caption: 'Hit TV Brands raised money on direct-response television production', position: 50 },
  { slug: 'steve-madden-stratton-oakmont-securities-fraud', query: 'New York Stock Exchange trading floor', caption: 'The Stratton Oakmont stock fraud ran through public share offerings', position: 50 },
  { slug: 'paul-gulbronson-kelly-bonilla-citrona-homes-fraud', query: 'house renovation construction interior', caption: 'Investors paid for renovations on rental homes that were never done', position: 50 },
  { slug: 'kerr-kriisa-fake-family-emergency-fraud', query: 'college basketball arena game', caption: 'Kriisa was a college basketball player when the scheme ran', position: 50 },
  { slug: 'jeong-sang-ho-delio-crypto-fraud', query: 'Seoul South Korea skyline', caption: 'Seoul, where Delio operated as a "digital asset bank"', position: 45 },
  { slug: 'steven-long-universal-wealth-preservation-fraud', query: 'Birmingham England city centre', caption: 'England, where savers were moved into the pension scheme', position: 45 },
  { slug: 'terry-green-universal-roofs-fraud', query: 'roof tiles roofing work house', caption: 'Roofing work that was paid for twice and never properly done', position: 50 },
  { slug: 'thomas-lemmen-schererville-insurance-fraud', query: 'Indiana Statehouse Indianapolis', caption: 'Indiana, where Lemmen wrote policies clients never applied for', position: 45 },
  { slug: 'daejon-love-taylor-chan-fake-nfl-romance-scam', query: 'Levi\u2019s Stadium Santa Clara', caption: 'The scheme used a fabricated connection to a San Francisco 49ers player', position: 50 },
  { slug: 'leong-koon-wah-singliworld-singliforex-pyramid-scheme', query: 'Kuala Lumpur Malaysia skyline', caption: 'Malaysia, where Singliworld faked a decade of forex trading', position: 45 },
  { slug: 'matthew-onofrio-bigger-pockets-real-estate-fraud', query: 'commercial real estate building exterior', caption: 'Onofrio built a following on commercial real estate deal-making', position: 50 },
  { slug: 'brett-deborah-rosen-rb-capital-partners-fraud', query: 'stock certificate share document', caption: 'RB Capital Partners ran a paid stock-promotion scheme', position: 50 },
  { slug: 'andrea-kent-shannon-fictitious-financial-instruments-tax-fraud', query: 'Internal Revenue Service building Washington', caption: 'The IRS, which the $57 million in fictitious refund claims were filed against', position: 45 },
  { slug: 'onur-simsek-defense-procurement-fraud-fugitive', query: 'United States Navy aircraft carrier', caption: 'Parts sold as "Made in the USA" reached Navy carriers and Army vehicles', position: 50 },
  { slug: 'rey-grabato-nria-ponzi-scheme-fugitive', query: 'Manila Philippines skyline', caption: 'The Philippines, where Grabato went before the NRIA collapse', position: 45 },
  { slug: 'rodney-dean-allen-ka-investments-missing-broker-fraud', query: 'Snake River Idaho canyon', caption: 'The Snake River near Boise, where Allen was last seen', position: 50 },
  { slug: 'sevindik-huseynov-vonyes-medicare-advantage-fraud', query: 'orthopedic back brace medical', caption: 'Orthotic braces billed to Medicare for patients who did not need them', position: 50 },
  { slug: 'sheryl-williams-stapleton-robotics-management-kickback-fraud', query: 'Albuquerque New Mexico city', caption: 'New Mexico, where the classroom robotics contracts were steered', position: 45 },
  { slug: 'patrick-james-edward-james-first-brands-fraud', query: 'auto parts warehouse shelves', caption: 'First Brands\u2019 auto-parts business was real; billions in invoices were not', position: 50 },
  { slug: 'richard-mcneil-norristown-ponzi-scheme', query: 'Norristown Pennsylvania', caption: 'Norristown, Pennsylvania, where McNeil raised money from 50 investors', position: 45 },
  { slug: 'paul-parmar-constellation-healthcare-fraud', query: 'hospital medical billing office', caption: 'Constellation sold medical billing services; a key subsidiary was fictitious', position: 50 },
  { slug: 'rathnakishore-giri-crypto-ponzi-scheme', query: 'Columbus Ohio skyline', caption: 'Ohio, where Giri ran the crypto fund from his parents\u2019 home', position: 45 },
  { slug: 'parker-terrill-austin-embarcadero-capital-fraud', query: 'San Francisco Embarcadero waterfront', caption: 'San Francisco, where Embarcadero Capital was based', position: 45 },
  { slug: 'otis-jackson-sito-capital-affordable-housing-fraud', query: 'Baltimore Maryland rowhouses', caption: 'Park Heights, Baltimore, where the housing programme existed only on paper', position: 50 },
  { slug: 'robert-desselle-genetic-testing-kickback-scheme', query: 'grocery store aisle shoppers', caption: 'Swab samples were collected from shoppers outside grocery stores', position: 50 },
  { slug: 'riadh-fakhoury-vestech-partners-vc-fraud', query: 'Scottsdale Arizona city', caption: 'Arizona, where Vestech raised money for its venture funds', position: 45 },
  { slug: 'rodney-rippe-straight-line-remodeling-fraud', query: 'home remodeling construction unfinished', caption: 'Deposits were taken for remodelling work that was never started', position: 50 },
  { slug: 'stephen-swensen-crew-capital-ponzi-scheme', query: 'Salt Lake City federal courthouse', caption: 'The federal courthouse in Salt Lake City, where the Crew Capital case was brought', position: 45 },
  { slug: 'robert-higgins-first-state-depository-fraud', query: 'silver bullion bars vault storage', caption: 'Customers paid to store precious metals that were sold out from under them', position: 50 },
  { slug: 'stephan-schafer-jonas-koller-sk-group-ponzi-scheme', query: 'Frankfurt am Main Germany skyline', caption: 'Germany, where the S&K Group sold property investments to retail investors', position: 45 },
  { slug: 'qnet-goldquest-pyramid-scheme-india', query: 'Chennai India city', caption: 'India, whose courts found the multi-level marketing operation a pyramid scheme', position: 45 },
  { slug: 'heinz-roth-pr-container-ponzi-scheme', query: 'Hamburg container terminal', caption: 'A container terminal. P&R sold investors boxes that did not exist', position: 50 },
  { slug: 'soapy-smith-skagway-klondike-con-empire', query: 'Soapy Smith Skagway', caption: 'Jefferson "Soapy" Smith, who ran the Skagway con empire', position: 40 },
  { slug: 'barry-silbert-genesis-gemini-earn-dcg-fraud', query: 'Manhattan New York skyline', caption: 'New York, where the Genesis and Gemini Earn case was brought', position: 45 },
  { slug: 'charles-smethurst-dolphin-trust-german-property-group-fraud', query: 'Hanover Germany historic building', caption: 'Germany, where Dolphin Trust sold stakes in listed-building restorations', position: 45 },
  { slug: 'adam-rundle-robinvest-safe-fraud', query: 'Perth Western Australia skyline', caption: 'Australia, where Rundle posed as a licensed adviser using a borrowed identity', position: 45 },
  { slug: 'storm-financial-double-gearing-collapse', query: 'Townsville Queensland Australia', caption: 'Townsville, where Storm Financial was founded', position: 45 },
  { slug: 'nathans-finance-vtl-prospectus-fraud', query: 'Wellington New Zealand city', caption: 'New Zealand, where Nathans Finance raised money on its prospectus', position: 45 },
  { slug: 'andrew-skeene-global-forestry-investments-teak-fraud', query: 'teak tree plantation forest', caption: 'A teak plantation of the kind investors were told they owned a plot of', position: 50 },
  { slug: 'thalbinder-shailu-poonian-ose-corp-pump-and-dump', query: 'Vancouver British Columbia skyline', caption: 'British Columbia, where the Poonians ran the pump-and-dump', position: 45 },
  { slug: 'otto-spork-sextant-capital-glacier-fraud', query: 'glacier Iceland ice', caption: 'An Icelandic glacier. Sextant\u2019s fund value rested on glacier water bottling', position: 50 },
  { slug: 'lance-ryan-blackfortfx-christchurch-forex-fraud', query: 'Christchurch earthquake damage 2011', caption: 'Christchurch after the earthquakes, whose insurance payouts the scheme targeted', position: 50 },
  { slug: 'david-natasha-sharpe-bridging-finance-fraud', query: 'Toronto Ontario skyline', caption: 'Toronto, where Bridging Finance managed $2 billion before its collapse', position: 45 },
  { slug: 'phillip-nunn-patrick-mccreesh-blackmore-bond-fraud', query: 'Manchester England city centre', caption: 'Manchester, where Blackmore Bond raised \u00a346 million from retail investors', position: 45 },
  { slug: 'victor-ogiemwonyi-partnership-securities-share-fraud', query: 'Nigerian Stock Exchange Lagos', caption: 'Nigeria, where the shares were sold without the client\u2019s knowledge', position: 45 },
  { slug: 'neil-paulson-help-the-vets-charity-fraud', query: 'United States military veterans ceremony', caption: 'Donations solicited for veterans mostly funded the charity\u2019s own operators', position: 50 },
  { slug: 'christophe-rocancourt-fake-rockefeller-con-man', query: 'Hamptons Southampton New York house', caption: 'The Hamptons, where Rocancourt passed himself off as a Rockefeller', position: 50 },
  { slug: 'daniel-reeve-kitchener-ontario-ponzi-scheme', query: 'Kitchener Ontario city hall', caption: 'Kitchener, Ontario, where Reeve ran the scheme', position: 45 },
  { slug: 'henry-smith-supreme-roofing-fareham-fraud', query: 'Fareham Hampshire England', caption: 'Fareham, Hampshire, where the roofing scheme returned to the same victims', position: 45 },
  { slug: 'declan-nowell-investing4you-forex-ponzi-scheme', query: 'Sheffield England city centre', caption: 'England, where Investing4you raised \u00a39 million on fake forex returns', position: 45 },
  { slug: 'zakia-khan-medicaid-adult-day-care-fraud', query: 'adult day care centre seniors activity', caption: 'Adult day care services billed to Medicaid through a kickback scheme', position: 50 },
  { slug: 'theodore-miller-wolf-of-west-virginia-fraud', query: 'Charleston West Virginia city', caption: 'West Virginia, where Miller built a property empire on investor money', position: 45 },
  { slug: 'waldon-fenster-last-mile-loan-fraud', query: 'casino slot machines Las Vegas', caption: 'Fund money paid for roughly 200 casino trips', position: 50 },
  { slug: 'vetlink-solutions-veterans-disability-fraud', query: 'Department of Veterans Affairs building', caption: 'The VA twice told VetLink to stop filing the claims', position: 45 },
  { slug: 'tiffany-yang-spread-ex-pig-butchering-scam', query: 'Flushing Queens New York street', caption: 'Flushing, Queens, where the "Spread Ex" operation was run from a condo', position: 45 },
  { slug: 'vanguard-holdings-group-bond-trading-ponzi-scheme', query: 'United States Treasury bond certificate', caption: 'The scheme claimed to trade bonds on investors\u2019 behalf', position: 50 },
  { slug: 'tai-lopez-alex-mehr-retail-ecommerce-ventures-ponzi-scheme', query: 'RadioShack store front', caption: 'A RadioShack storefront — the brand revival the notes were sold against', position: 50 },
  { slug: 'anthony-torre-superannuation-theft-fraud', query: 'Derby Western Australia town', caption: 'Derby, Western Australia, where the property deal never existed', position: 50 },
  { slug: 'craig-warriner-bhi-trust-ponzi-scheme', query: 'Pretoria South Africa city', caption: 'South Africa, where the BHI Trust ran for years on word-of-mouth trust', position: 45 },
  { slug: 'toby-whittaker-store-first-pension-fraud', query: 'self storage units facility', caption: 'Storage pods sold into pensions as an income-producing asset', position: 50 },
  { slug: 'mina-tadrus-ai-hedge-fund-coptic-fraud', query: 'Coptic Orthodox church interior', caption: 'Tadrus raised money from members of his own Coptic church community', position: 50 },
  { slug: 'thomas-aroha-tuira-christchurch-ponzi-scheme', query: 'Christchurch New Zealand city', caption: 'Christchurch, where the scheme spread through a M\u0101ori community', position: 45 },
  { slug: 'waxman-philip-services-copper-fraud', query: 'copper cathode metal industry', caption: 'Copper trading losses hidden from Philip Services\u2019 books', position: 50 },
  { slug: 'william-tierney-scam-political-action-committees', query: 'United States Capitol Washington', caption: 'Donors gave to political action committees that spent almost nothing on politics', position: 45 },
  { slug: 'matthew-turnipseede-sports-betting-ponzi-scheme', query: 'sportsbook betting odds board', caption: 'The sports-betting algorithm investors funded did not exist', position: 50 },
  { slug: 'kenny-dirk-van-der-spek-k-and-k-strategies-ponzi-scheme', query: 'Amsterdam Netherlands canal city', caption: 'The "hedge fund" took investor money but never actually traded', position: 45 },
  { slug: 'fake-invoice-unordered-services-business-scam-guide', query: 'invoice paperwork office desk', caption: 'Fake invoices arrive looking like routine bills a business has already incurred', position: 50 },
  { slug: 'coding-bootcamp-income-share-agreement-scam-guide', query: 'programming code computer screen classroom', caption: 'Coding bootcamps sold income share agreements as an alternative to loans', position: 50 },
  { slug: 'lost-pet-scam-ransom-good-samaritan-guide', query: 'lost dog missing pet poster', caption: 'Lost-pet posters give scammers everything they need to fake a sighting', position: 50 },
  { slug: 'arsen-lusher-trucking-ponzi-scheme', query: 'semi truck delivery fleet', caption: 'The trucking contracts Lusher raised capital against did not support the returns promised', position: 50 },
  { slug: 'stephen-ehrlich-voyager-digital-fraud', query: 'Toronto Ontario financial district', caption: 'Toronto, where Voyager Digital was listed before the crypto lender collapsed', position: 45 },
  { slug: 'dieter-breitkreuz-phoenix-kapitaldienst-ponzi-scheme', query: 'Frankfurt am Main Germany skyline', caption: 'Frankfurt, where Phoenix Kapitaldienst ran its managed-futures scheme', position: 45 },
  { slug: 'brian-hunter-amaranth-advisors-natural-gas-collapse', query: 'natural gas pipeline compressor station', caption: 'Natural gas infrastructure. Amaranth lost $6.6 billion betting on its price', position: 50 },
  { slug: 'patrick-halligan-archegos-cfo-fraud', query: 'Manhattan Midtown office towers', caption: 'Manhattan, where Archegos misrepresented its exposure to its lending banks', position: 45 },
  { slug: 'salvatore-ligresti-fondiaria-sai-fraud', query: 'Milan Italy city skyline', caption: 'Milan, where Fondiaria-SAI was headquartered', position: 45 },
  { slug: 'joseph-ossorio-david-heuwetter-drysdale-government-securities-collapse', query: 'Wall Street New York financial district', caption: 'Wall Street, where Drysdale\u2019s repo trades nearly broke the government bond market', position: 45 },
  { slug: 'steven-perkins-pvm-oil-drunk-trading-market-abuse', query: 'crude oil barrels storage', caption: 'Perkins\u2019 unauthorised overnight trades moved the global price of crude', position: 50 },
  { slug: 'stuart-pearson-langbar-international-fraud', query: 'London Stock Exchange building', caption: 'Langbar was listed in London; the Brazilian deposit backing its value never existed', position: 45 },
  { slug: 'yin-guangxia-china-accounting-fraud', query: 'Ningxia China landscape', caption: 'Ningxia, where Yinguangxia claimed the export operation its books were built on', position: 50 },
  { slug: 'fake-bureau-of-prisons-release-scam-guide', query: 'federal correctional institution building United States', caption: 'A federal prison. The Bureau of Prisons never charges families for release or home confinement', position: 50 },
  { slug: 'carl-cushnie-versailles-group-fraud', query: 'Old Bailey Central Criminal Court London', caption: 'The Old Bailey, where Cushnie was convicted; most of Versailles\u2019 trade finance turnover was fictitious', position: 45 },
  { slug: 'marcel-de-vries-vestia-derivatives-fraud', query: 'Vestia Rotterdam', caption: 'A Rotterdam housing block. Vestia was the Netherlands\u2019 largest social housing association when the derivatives losses hit', position: 50 },
  { slug: 'hacked-email-account-recovery', query: 'two factor authentication security key', caption: 'A security key. Two-factor authentication is what stops a recovered account being taken straight back', position: 50 },
  { slug: 'tim-johnston-firepower-fuel-pill-fraud', query: 'car engine fuel injector', caption: 'A car engine. Firepower\u2019s fuel pill was independently tested and found to do nothing', position: 50 },
  { slug: 'stanislaw-burzynski-antineoplaston-cancer-clinic-fraud', query: 'Texas Medical Center Houston', caption: 'Houston, where the clinic sold an unapproved cancer therapy to desperate families', position: 45 },
  { slug: 'samuel-caster-mannatech-glyconutrient-marketing-fraud', query: 'dietary supplement capsules bottle', caption: 'Dietary supplements. Texas called Mannatech\u2019s disease-cure claims illegal', position: 50 },
  { slug: 'william-miller-520-percent-franklin-syndicate-fraud', query: 'Brooklyn New York 1900 street scene', caption: 'Brooklyn in Miller\u2019s era. His Franklin Syndicate promised 520% a year, two decades before Ponzi', position: 50 },
  { slug: 'apiruk-kothi-forex-3d-ponzi-scheme-thailand', query: 'Bangkok Thailand skyline', caption: 'Bangkok \u2014 Forex-3D took deposits from nearly 10,000 Thai investors', position: 45 },
  { slug: 'rafael-olvera-amezcua-ficrea-fraud-mexico', query: 'Mexico City skyline Reforma', caption: 'Mexico City, where Ficrea\u2019s collapse wiped out 6,800 savers', position: 45 },
  { slug: 'tank-black-cash-4-titles-athlete-fraud', query: 'American football stadium NFL', caption: 'Black represented NFL and NBA players before the scheme collapsed', position: 50 },
  { slug: 'fake-antivirus-tech-support-renewal-scam-guide', query: 'antivirus software computer screen', caption: 'A browser security warning. The fake renewal invoice is only the bait \u2014 the \u201Crefund\u201D call is where the theft happens', position: 50 },
  { slug: 'fake-irs-fresh-start-tax-debt-relief-scam-guide', query: 'Internal Revenue Service building Washington', caption: 'The IRS charges no fee to apply for its own installment and offer programs', position: 45 },
  { slug: 'preneed-funeral-trust-fraud-guide', query: 'funeral home hearse', caption: 'Money paid years in advance must sit in a trust \u2014 ask for written proof that it does', position: 50 },
  { slug: 'real-estate-deed-solicitation-scam-guide', query: 'property deed document land title', caption: 'Your county recorder sells the same deed copy for a few dollars', position: 50 },
  { slug: 'roger-levitt-tlg-financial-adviser-fraud', query: 'City of London Lloyds building', caption: 'The City of London, where the Levitt Group sold investment advice to its clients', position: 45 },
  { slug: 'fake-parking-traffic-ticket-text-scam-guide', query: 'parking ticket windscreen car', caption: 'A real citation goes on the windscreen or in the post \u2014 not to your phone by text with a payment link', position: 50 },
  { slug: 'abdul-shamji-johnson-matthey-bankers-collapse', query: 'Bank of England Threadneedle Street', caption: 'The Bank of England, which mounted the rescue when Johnson Matthey Bankers collapsed in 1984', position: 45 },
  { slug: 'social-media-profile-cloning-scam-guide', query: 'social media app icons smartphone screen', caption: 'A cloned profile copies your public photos and name \u2014 your real account is untouched, which is why you never see a breach warning', position: 50 },
  { slug: 'david-bullen-national-australia-bank-forex-scandal', query: 'Melbourne central business district skyline', caption: 'Melbourne, where NAB\u2019s currency options desk hid its losses until the board found them', position: 45 },
  { slug: 'joseph-yellow-kid-weil-chicago-con-man', file: 'Joseph "Yellow Kid" Weil 1918.jpg', caption: 'Joseph \u201CYellow Kid\u201D Weil, photographed in 1918', position: 40 },
  { slug: 'north-korean-remote-it-worker-fraud-guide', query: 'laptop video call remote work desk', caption: 'A remote interview. The tell is a candidate who will not turn the camera on, or whose pay goes to an address that keeps changing', position: 50 },
  { slug: 'frederic-pierucci-alstom-tarahan-bribery-fcpa', query: 'coal fired power station Indonesia', caption: 'A coal-fired power plant. The Tarahan contract was won with bribes paid through consultants', position: 50 },
  { slug: 'neil-woodford-equity-income-fund-collapse', query: 'London Stock Exchange building', caption: 'The fund held unlisted stakes it could not sell fast enough when investors asked for their money back', position: 45 },
  { slug: 'obituary-bereavement-scam-guide', query: 'newspaper obituary page print', caption: 'A published death notice hands a stranger the names, dates and relationships needed to sound like family', position: 50 },
  { slug: 'siddharth-jawahar-swiftarc-capital-ponzi-scheme', query: 'Manhattan office towers Midtown', caption: 'New York, where Swiftarc raised money for a fund that was paying earlier investors', position: 45 },
  { slug: 'martin-schlaepfer-malom-group-fugitive-fraud', query: 'Zurich Switzerland city', caption: 'Switzerland, where the Malom Group fronted its advance-fee scheme from', position: 45 },
  // A search for 'auction gavel bidding' returned a portrait painting by
  // Hobbe Smith, which shows nothing to do with an auction. Pinned to the
  // file instead: an auction hammer, which is what the guide is about.
  { slug: 'online-auction-fraud-shill-bidding-guide', file: 'Bid hammer.jpg', caption: 'An auction hammer \u2014 the bids driving the price up came from accounts the seller controlled', position: 50 },
  { slug: 'neil-bush-silverado-savings-loan-collapse', query: 'Denver Colorado downtown skyline', caption: 'Denver, where Silverado lent to the developers sitting on its own board', position: 45 },
  { slug: 'farm-equipment-impersonation-scam-guide', query: 'tractor farm equipment dealership', caption: 'A fake dealer listing undercuts the market, takes a wire deposit, and the tractor never ships', position: 50 },
  { slug: 'zakia-khan-medicaid-adult-day-care-fraud', query: 'Brooklyn New York street', caption: 'Brooklyn, where Khan’s Medicaid-funded adult day care centers were licensed to operate', position: 45 },
  { slug: 'matthew-turnipseede-sports-betting-ponzi-scheme', query: 'Las Vegas Nevada skyline', caption: 'Las Vegas, where Turnipseede pitched his sports-betting algorithm to investors', position: 45 },
  { slug: 'zhongzhi-enterprise-group-collapse', query: 'Beijing China financial district skyline', caption: 'Beijing — Zhongzhi’s trust and wealth-management units were part of China’s shadow-banking sector', position: 45 },
  { slug: 'daniel-vorcaro-banco-master-collapse', query: 'Brazilian real currency banknotes', caption: 'Brazilian real banknotes — Banco Master offered CDB deposit rates far above the market benchmark to attract depositors', position: 50 },
  { slug: 'doxo-steve-shivers-roger-parks-bill-pay-junk-fees', query: 'utility bill paperwork payment', caption: 'A utility bill — Doxo charged consumers a fee to pay bills they could pay free directly with their biller', position: 50 },
  { slug: 'mikheil-biniashvili-milton-group-pumats-scam-software', query: 'Tirana Albania city', caption: 'Tirana, Albania, where Biniashvili’s call-center network of fake trading platforms was based', position: 45 },
  { slug: 'david-murcia-guzman-dmg-colombia-ponzi-scheme', query: 'Bogota Colombia skyline', caption: 'Colombia, where DMG sold prepaid cards loaded with investor funds across dozens of cities before its 2008 collapse', position: 45 },
  { slug: 'rishi-kamlesh-agarwal-abg-shipyard-bank-fraud', query: 'shipyard dry dock ship construction', caption: 'A shipyard dry dock — ABG Shipyard built ships and offshore vessels before its $2.8 billion bank-consortium fraud collapse', position: 50 },
  { slug: 'cody-easterday-ghost-cattle-fraud', query: 'cattle feedlot ranch', caption: 'A cattle feedlot of the kind Easterday Ranches operated in the Pacific Northwest', position: 50 },
  { slug: 'james-black-abc-learning-centres-accounting-fraud', query: 'Brisbane Australia skyline', caption: 'Brisbane, where ABC Learning Centres was founded and grew into the world’s largest listed childcare operator', position: 45 },
  { slug: 'steve-burns-lordstown-motors-endurance-preorder-fraud', query: 'Lordstown Ohio assembly plant', caption: 'The Lordstown, Ohio plant where Lordstown Motors planned to build the Endurance electric pickup', position: 45 },
  { slug: 'david-p-bloom-wall-street-whiz-kid-repeat-fraud', query: 'Wall Street Manhattan financial district', caption: 'Wall Street — Bloom ran the same investment scheme from Manhattan across nearly four decades', position: 45 },
  { slug: 'sachin-dev-duggal-builder-ai-fraud', query: 'London England financial district skyline', caption: 'London, where Builder.ai was headquartered before its 2025 collapse', position: 45 },
  { slug: 'antonio-camacho-gescartera-fraud', query: 'Madrid Spain city', caption: 'Madrid, where Gescartera Dinero was based and diverted client funds from Spanish charities and religious orders', position: 45 },
  { slug: 'francius-marganda-easy-transfer-global-transfer-ponzi', query: 'New York City skyline', caption: 'New York, where Marganda promoted Easy Transfer and Global Transfer within the Indonesian-American community', position: 45 },
  { slug: 'joel-apolinario-kapa-community-ministry-ponzi-scheme', query: 'Philippine peso banknotes', caption: 'Philippine peso banknotes — Kapa’s roughly 5 million members were promised religiously-framed monthly returns', position: 50 },
  { slug: 'john-lytle-bill-patterson-penn-square-continental-illinois-kickback', query: 'Chicago Illinois skyline', caption: 'Chicago, home of Continental Illinois National Bank, which needed a $4.5 billion FDIC bailout after Penn Square’s collapse', position: 45 },
  { slug: 'michael-thomson-london-capital-finance-mini-bond-ponzi-scheme', query: 'London England financial district skyline', caption: 'London, where London Capital & Finance was based before its 2019 collapse', position: 45 },
  { slug: 'james-corr-cattles-accounting-scandal', query: 'British pound sterling banknotes', caption: 'British pound banknotes — Welcome Financial Services extended door-to-door subprime loans across Britain', position: 50 },
  { slug: 'kazuhiko-asakawa-aij-pension-fraud', query: 'Tokyo Japan financial district skyline', caption: 'Tokyo, where AIJ Investment Advisors was based', position: 45 },
  { slug: 'konrad-kakolewski-getback-bond-fraud', query: 'Warsaw Poland skyline', caption: 'Warsaw, home of the stock exchange where GetBack completed its 2017 IPO', position: 45 },
  { slug: 'ma-xingtian-kangmei-pharmaceutical-accounting-fraud', query: 'Shanghai Stock Exchange building', caption: 'The Shanghai Stock Exchange, where Kangmei Pharmaceutical was listed', position: 45 },
  { slug: 'hughes-kahn-prophecy-asset-management-collapse', query: 'New York City financial district Wall Street', caption: 'New York, where Prophecy Asset Management was based', position: 45 },
  { slug: 'johnson-lee-jjptr-forex-ponzi-scheme', query: 'Penang Malaysia George Town', caption: 'Penang, Malaysia, where Johnson Lee launched JJPTR', position: 45 },
  { slug: 'ihor-kolomoisky-privatbank-fraud', query: 'Kyiv Ukraine skyline', caption: 'Kyiv — PrivatBank became Ukraine’s largest bank by assets and depositors under Kolomoisky', position: 45 },
  { slug: 'modern-tech-ifan-pincoin-vietnam-crypto-fraud', query: 'Ho Chi Minh City Vietnam skyline', caption: 'Ho Chi Minh City, where Modern Tech promoted the iFan and Pincoin tokens', position: 45 },
  { slug: 'catalytic-converter-theft-prevention-guide', query: 'catalytic converter car exhaust part', caption: 'A catalytic converter — the small, easily-removed exhaust part thieves target for its platinum-group metals', position: 50 },
  { slug: 'fake-class-action-settlement-notice-scam', query: 'gavel courtroom law', caption: 'A courtroom gavel — scammers fabricate fake settlement notices piggybacking on real, newsworthy class-action cases', position: 50 },
  { slug: 'petr-smetka-h-system-housing-fraud', query: 'Prague Czech Republic city', caption: 'Czech Republic, where H-System left roughly 1,000 families’ savings tied up in half-built houses', position: 45 },
  { slug: 'martin-pucher-commerzialbank-mattersburg-collapse', query: 'Vienna Austria skyline', caption: 'Austria, where Commerzialbank Mattersburg’s collapse became the third-largest insolvency in the country’s history', position: 45 },
  { slug: 'daniel-schatt-joseph-podulka-cred-llc-crypto-fraud', query: 'cryptocurrency Bitcoin coins', caption: 'Cred LLC funneled customer cryptocurrency into undisclosed, unhedged loans before its 2020 bankruptcy', position: 50 },
  { slug: 'daniel-och-och-ziff-africa-bribery-scandal', query: 'New York City Manhattan financial district', caption: 'New York, where Och-Ziff Capital Management was based', position: 45 },
  { slug: 'roman-storm-tornado-cash-money-laundering', query: 'Ethereum cryptocurrency blockchain', caption: 'Tornado Cash was a cryptocurrency-mixing service built on the Ethereum blockchain', position: 50 },
  { slug: 'carl-channing-spence-aei-financial-meme-stock-ponzi', query: 'Houston Texas skyline', caption: 'Near Houston, Texas, where Spence ran the AEI Financial Ponzi scheme from Mont Belvieu', position: 45 },
  { slug: 'ravi-parthasarathy-ilfs-collapse', query: 'Mumbai India skyline', caption: 'Mumbai, where IL&FS was headquartered before its 2018 collapse', position: 45 },
  { slug: 'michael-palleschi-fte-networks-accounting-fraud', query: 'fiber optic cable network', caption: 'FTE Networks built fiber-optic and telecom infrastructure before its accounting fraud collapse', position: 50 },
  { slug: 'byju-raveendran-byjus-edtech-fraud', query: 'Bangalore India skyline', caption: 'Bangalore (Bengaluru), where Byju’s was headquartered', position: 45 },
  { slug: 'harbinder-singh-sethi-tegeta-escrow-scandal-tanzania', query: 'Dar es Salaam Tanzania skyline', caption: 'Dar es Salaam, Tanzania, where the Tegeta Escrow account scandal unfolded', position: 45 },
  { slug: 'harold-roth-continental-vending-fraud', query: 'vintage vending machine', caption: 'A vintage vending machine — Continental Vending Machine Corporation was the real business Roth used to mask the fraud', position: 50 },
  { slug: 'salman-nuryanto-pandawa-group-indonesia-ponzi-scheme', query: 'Jakarta Indonesia skyline', caption: 'Jakarta, Indonesia — the Pandawa Group cooperative promised outsized returns to hundreds of thousands of depositors nationwide', position: 45 },
];
